/* ARENA ULTIMATE — Etapa 8/10: Combate 5.0 */
(()=>{const $=id=>document.getElementById(id),S=window.AU_SAVE;if(!S)return;S.combat5??={essence:0,fury:0,cooldowns:{}};const sp=()=>{let b=S.beasts.find(x=>x.id===S.assimilation?.active);return b&&(window.AU_SPECIES||[]).find(x=>x.id===b.species)},beast=()=>S.beasts.find(x=>x.id===S.assimilation?.active),form=()=>S.transformation?.form||'human';
const MOD={human:{speed:1,damage:1,reach:1,def:1},manifest:{speed:1.08,damage:1.1,reach:1.03,def:1.03},hybrid:{speed:1.18,damage:1.22,reach:1.15,def:1.08},avatar:{speed:1.28,damage:1.38,reach:1.25,def:1.15}};
function profile(){let s=sp(),m={...MOD[form()]};if(!s)return m;if(s.arch==='Predador'){m.damage*=1.12;m.speed*=1.06}if(s.arch==='Guardião')m.def*=1.2;if(s.arch==='Duelista')m.speed*=1.15;if(s.arch==='Colosso'){m.damage*=1.18;m.speed*=.9}if(s.arch==='Espírito')m.reach*=1.15;return m}
function activeReady(level){let b=beast();return b&&(b.mastery||0)>=level}function damage(base){let p=profile(),syn=beast()&&window.AU_SYNERGY?window.AU_SYNERGY(beast()).total:0;return Math.round(base*p.damage*(1+syn/500))}function gain(n){S.combat5.essence=Math.min(100,S.combat5.essence+n);hud()}
function hud(){let e=$('combatEssence'),f=$('combatForm'),s=sp();if(e)e.style.width=S.combat5.essence+'%';if(f)f.textContent=s?`${s.icon} ${form().toUpperCase()}`:'SEM FERA';let ult=$('beastUlt');if(ult)ult.disabled=!activeReady(5)||S.combat5.essence<100}
function useSkill(slot){let s=sp(),b=beast();if(!s||!b)return window.AU_MODAL?.('SEM ASSIMILAÇÃO','Assimile uma fera para usar técnicas espirituais.');let req=slot===1?2:3;if(!activeReady(req))return window.AU_MODAL?.('TÉCNICA BLOQUEADA',`Exige Domínio ${req}/5.`);let cost=slot===1?28:42;if(S.combat5.essence<cost)return;S.combat5.essence-=cost;let d=damage(slot===1?24:34);window.AU_COMBAT5_DAMAGE?.(d,slot===1?s.skills[0]:s.skills[1]);hud()}
function ultimate(){let s=sp();if(!s||!activeReady(5)||S.combat5.essence<100)return;S.combat5.essence=0;let d=damage(62);window.AU_COMBAT5_DAMAGE?.(d,s.ultimate);hud()}
function cycleTransform(){let b=beast();if(!b)return;let m=b.mastery||0,seq=['human'];if(m>=2)seq.push('manifest');if(m>=4)seq.push('hybrid');if(m>=5)seq.push('avatar');let i=(seq.indexOf(form())+1)%seq.length;S.transformation.form=seq[i];localStorage.setItem('AU5',JSON.stringify(S));hud();window.AU_MODAL?.('FORMA DE COMBATE',seq[i].toUpperCase())}
window.AU_COMBAT5_START=()=>{S.combat5.essence=25;hud()};window.AU_COMBAT5_HIT=()=>gain(9);window.AU_COMBAT5_PROFILE=profile;window.AU_COMBAT5_DAMAGE_VALUE=damage;
function inject(){let battle=$('battle');if(!battle||$('spiritHud'))return;let sh=document.createElement('div');sh.id='spiritHud';sh.className='spiritHud';sh.innerHTML=`<div><span id=combatForm>SEM FERA</span><div class=spiritBar><i id=combatEssence></i></div></div>`;battle.insertBefore(sh,$('arena'));let ctl=battle.querySelector('.ctl'),skills=document.createElement('div');skills.className='spiritActions';skills.innerHTML=`<button id=beastSkill1 class=b>✦ I</button><button id=beastSkill2 class=b>✦ II</button><button id=combatTransform class='b p'>◈ FORMA</button><button id=beastUlt class=b>☄ ULT</button>`;ctl.parentNode.insertBefore(skills,ctl);$('beastSkill1').onclick=()=>useSkill(1);$('beastSkill2').onclick=()=>useSkill(2);$('beastUlt').onclick=ultimate;$('combatTransform').onclick=cycleTransform;hud()}
const css=document.createElement('style');css.textContent='.spiritHud{height:42px;background:#17101ddd;border-block:1px solid #674b76;padding:5px 12px;font-size:10px}.spiritBar{height:8px;background:#09070c;border:1px solid #654c72;margin-top:4px}.spiritBar i{display:block;height:100%;background:linear-gradient(90deg,#6845a0,#d68ef0);transition:width .2s}.spiritActions{display:grid;grid-template-columns:repeat(4,1fr);gap:4px;padding:5px;background:#151018}.spiritActions .b{min-height:42px;font-size:10px}';document.head.appendChild(css);setTimeout(inject,250);
})();