/* ARENA ULTIMATE — Etapa 5/10: exploração, encontro e subjugação */
(()=>{const $=id=>document.getElementById(id),S=window.AU_SAVE;if(!S)return;S.world??={unlocked:['velaria'],bestiary:[]};S.world.bestiary??=[];S.world.regions??=['bosque'];
const REGIONS=[{id:'bosque',name:'Bosque Viridiano',icon:'🌲',desc:'Floresta ancestral próxima a Velaria.',species:['thornstag','tideclaw','pyrofang'],danger:1},{id:'rubras',name:'Terras Rubras',icon:'🌋',desc:'Cinzas, rocha quente e predadores de fogo.',species:['pyrofang','stoneback'],danger:2},{id:'picos',name:'Picos da Tormenta',icon:'⛈️',desc:'Montanhas onde relâmpagos nunca cessam.',species:['stormhawk','stoneback'],danger:3},{id:'eclipse',name:'Ruínas do Eclipse',icon:'🌑',desc:'Ruínas espirituais tomadas pela sombra.',species:['nightlynx','mistwyrm'],danger:4}];
let wild=null,will=0,lock=false;function save(){localStorage.setItem('AU5',JSON.stringify(S))}function species(){return window.AU_SPECIES||[]}function sp(id){return species().find(x=>x.id===id)}function make(spc){let primordial=Math.floor(Math.random()*25);return{id:spc.id+'-'+Date.now(),species:spc.id,name:spc.name,level:1+Math.floor(Math.random()*4),xp:0,affinity:8,potential:55+Math.floor(Math.random()*41),bloodline:{base:100-primordial,primordial},mastery:0,evolution:0,bonded:true}}
function open(){document.querySelectorAll('.s').forEach(x=>x.classList.add('x'));$('world').classList.remove('x');renderRegions()}
function renderRegions(){$('regionList').innerHTML=REGIONS.map((r,i)=>`<button class="region ${S.world.regions.includes(r.id)?'':'locked'}" data-region="${r.id}" ${S.world.regions.includes(r.id)?'':'disabled'}><strong>${r.icon} ${r.name}</strong><span>${r.desc}</span><small>Perigo ${'◆'.repeat(r.danger)}${S.world.regions.includes(r.id)?'':' · BLOQUEADO'}</small></button>`).join('');document.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>encounter(b.dataset.region))}
function encounter(id){let r=REGIONS.find(x=>x.id===id),pool=r.species.map(sp).filter(Boolean);if(!pool.length)return;let s=pool[Math.floor(Math.random()*pool.length)];wild={sp:s,hp:100,max:100,level:1+Math.floor(Math.random()*r.danger*2),region:r};will=100;lock=false;if(!S.world.bestiary.includes(s.id)){S.world.bestiary.push(s.id);save()}$('worldMap').classList.add('x');$('wildBattle').classList.remove('x');renderWild(`${s.name} selvagem surgiu! Enfraqueça-o antes de subjugar.`)}
function renderWild(text){if(!wild)return;$('wildIcon').textContent=wild.sp.icon;$('wildName').textContent=wild.sp.name.toUpperCase();$('wildMeta').textContent=`${wild.sp.nature}/${wild.sp.arch} · NV ${wild.level}`;$('wildHp').style.width=wild.hp+'%';$('wildWill').style.width=will+'%';$('wildText').textContent=text;$('subdue').disabled=wild.hp>45||lock}
function enemy(){if(!wild||lock)return;let d=7+Math.floor(Math.random()*10);$('wildText').textContent=`${wild.sp.name} contra-ataca. Você resiste ao impacto espiritual (${d}).`;will=Math.max(0,will-(2+Math.floor(Math.random()*5)));renderWild($('wildText').textContent)}
$('wildAttack').onclick=()=>{if(lock)return;wild.hp=Math.max(1,wild.hp-(14+Math.floor(Math.random()*15)));renderWild('Seu golpe enfraqueceu a fera.');setTimeout(enemy,250)};
$('wildTechnique').onclick=()=>{if(lock)return;let c=S.cultivation?.core,bonus=c&&c.nature===wild.sp.nature?12:4;wild.hp=Math.max(1,wild.hp-(10+bonus));will=Math.max(0,will-(8+bonus));renderWild('Sua essência pressiona o instinto da fera.');setTimeout(enemy,250)};
$('wildGuard').onclick=()=>{will=Math.max(0,will-8);renderWild('Você mantém posição e observa o fluxo espiritual.')};
$('subdue').onclick=()=>{if(wild.hp>45||lock)return;lock=true;$('spiritDuel').classList.remove('x');$('wildActions').classList.add('x');$('duelNeedle').style.left='8%';$('duelText').textContent='Toque SELAR quando o marcador estiver na zona central.';let start=performance.now();function tick(t){if(!lock)return;let p=(Math.sin((t-start)/330)+1)/2;$('duelNeedle').style.left=(4+p*88)+'%';requestAnimationFrame(tick)}requestAnimationFrame(tick)};
$('seal').onclick=()=>{if(!lock)return;let left=parseFloat($('duelNeedle').style.left),accuracy=Math.max(0,1-Math.abs(left-50)/46),core=S.cultivation?.core,compat=core?(core.nature===wild.sp.nature?0.18:0)+(core.archetype===wild.sp.arch?0.12:0):0,chance=.28+accuracy*.38+(1-wild.hp/100)*.22+compat;if(Math.random()<chance){let b=make(wild.sp);S.beasts.push(b);save();$('duelText').innerHTML=`PACTO ESTABELECIDO · ${wild.sp.name}<br>Potencial ${b.potential} · Primordial ${b.bloodline.primordial}%`;lock=false;setTimeout(()=>{window.AU_MODAL?.('PACTO ESTABELECIDO',`${wild.sp.icon} <b>${wild.sp.name}</b> aceitou o vínculo.<br><br>A fera foi enviada ao Santuário.`);exit()},650)}else{will=Math.max(0,will-28);$('duelText').textContent=will<=0?'A fera rompeu sua vontade e escapou.':'A fera rejeitou o selo. Tente novamente.';if(will<=0){lock=false;setTimeout(exit,700)}else{lock=false;$('spiritDuel').classList.add('x');$('wildActions').classList.remove('x');renderWild('O pacto falhou. A fera está mais inquieta.')}}};
function exit(){$('spiritDuel').classList.add('x');$('wildActions').classList.remove('x');$('wildBattle').classList.add('x');$('worldMap').classList.remove('x');wild=null;window.AU_RENDER_BEASTS?.();renderRegions()}
$('fleeWild').onclick=exit;$('worldBack').onclick=()=>window.AU_SHOW?.('u');window.AU_OPEN_WORLD=open;window.AU_REGIONS=REGIONS;})();