from pathlib import Path
import json, re, hashlib
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]; HTML=(ROOT/'dist/ARENA_FILHOS_DA_AREIA_PC.html').read_text(); reports=[]
def record(name,passed,detail=''):
 reports.append({'name':name,'passed':bool(passed),'detail':detail})
 print(name,passed,str(detail)[:250],flush=True)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
 context=browser.new_context(viewport={'width':1366,'height':900},device_scale_factor=1,accept_downloads=True)
 page=context.new_page();page.set_default_timeout(6000); errors=[];requests=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.on('request',lambda r:requests.append(r.url[:140]) if r.url.startswith(('http:','https:')) else None)
 context.route('**/*',lambda route:route.abort());context.set_offline(True)
 # Managed browser forbids all URL navigations. Run the actual document in about:blank;
 # localStorage is a test double. Real save logic also has separate Node tests.
 page.evaluate("""()=>{const store={};Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k],clear:()=>Object.keys(store).forEach(k=>delete store[k])}});window.__testStorage=store;}""")
 page.set_content(HTML,wait_until='load');page.wait_for_timeout(800)
 record('Inicialização offline e capa original',page.locator('[data-arena-ready=true]').count()==1 and page.locator('img').evaluate('(i)=>i.complete&&i.naturalWidth>500'))
 page.screenshot(path=str(ROOT/'dist/pc-home.png'))
 page.get_by_role('button',name='ENTRAR NO LUDUS').click();page.wait_for_timeout(400)
 record('Cidade ilustrada e navegação',page.locator('main[data-screen=camp]').count()==1 and page.get_by_role('button',name='FORJA',exact=True).count()==1)
 page.screenshot(path=str(ROOT/'dist/pc-town.png'))
 page.get_by_role('button',name='PERSONALIZAR',exact=False).first.click();page.wait_for_timeout(300)
 print('custombuttons',page.get_by_role('button').all_text_contents(),flush=True)
 print('inputs',page.get_by_role('textbox').count(),flush=True)
 page.get_by_role('textbox').first.fill('Thiago — Arena')
 page.wait_for_timeout(150)
 name=page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5')).character.name")
 record('Personalização gravada no Save v5',name=='Thiago — Arena',name)
 page.screenshot(path=str(ROOT/'dist/pc-character.png'))
 page.get_by_role('button',name='Voltar ao ludus',exact=True).click();page.get_by_role('button',name='FORJA',exact=True).click();page.wait_for_timeout(250)
 record('Forja original sem imagem quebrada',page.locator('main[data-screen=shop]').count()==1 and page.evaluate('Array.from(document.images).every(i=>i.complete&&i.naturalWidth>0)'))
 print('shopbuttons',page.get_by_role('button').all_text_contents()[-30:],flush=True)
 cards=page.locator('article').filter(has_text='Machado de Lenhador')
 if cards.count()==0: cards=page.locator('article').filter(has=page.get_by_role('button',name=re.compile('COMPRAR'))).filter(has=page.locator('button:not([disabled])'))
 print('purchase eligible',cards.count(),flush=True)
 # Buy the first affordable not-yet-owned weapon.
 if cards.count()>0:
  article=cards.first; weaponname=article.locator('h3').inner_text();before=page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5')).character.gold")
  article.get_by_role('button',name=re.compile('COMPRAR')).click();page.wait_for_timeout(150)
  after=page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5')).character")
  record('Compra, equipamento e débito de ouro',after['gold']<before and after['equipped']['weapon']!='sword-1',weaponname)
 page.screenshot(path=str(ROOT/'dist/pc-forge.png'))
 page.get_by_role('button',name='Equipar',exact=True).click();page.wait_for_timeout(250)
 record('Arsenal com equipamento visual',page.locator('main[data-screen=gear]').count()==1 and page.locator('canvas').count()>0)
 page.screenshot(path=str(ROOT/'dist/pc-armory.png'))
 page.get_by_role('button',name='Treinar',exact=True).click();page.wait_for_timeout(250)
 record('Atributos e três técnicas acessíveis',page.locator('main[data-screen=train]').count()==1 and 'Muralha' in page.locator('body').inner_text() and 'Duelista' in page.locator('body').inner_text())
 page.get_by_role('button',name='Arenas',exact=True).click();page.wait_for_timeout(250)
 record('Mapa, três arenas e 12 adversários',page.locator('main[data-screen=map]').count()==1 and 'Anfiteatro Solar' in page.locator('body').inner_text())
 page.screenshot(path=str(ROOT/'dist/pc-map.png'))
 page.get_by_role('button',name='Ajuda e configurações').click();page.wait_for_timeout(250)
 with page.expect_download() as download:
  page.get_by_role('button',name='EXPORTAR',exact=True).click()
 d=download.value;d.save_as(str(ROOT/'dist/browser-save.json'))
 saved=json.loads((ROOT/'dist/browser-save.json').read_text())
 code=page.get_by_role('textbox',name='Código de recuperação').input_value()
 record('Exportação de backup JSON + código ARENA5',saved['version']==5 and code.startswith('ARENA5:'))
 page.get_by_role('button',name='IMPORTAR CÓDIGO',exact=True).click();page.get_by_role('button',name='CONFIRMAR IMPORTAÇÃO',exact=True).click();page.wait_for_timeout(200)
 record('Importação com confirmação retorna ao ludus',page.locator('main[data-screen=camp]').count()==1)
 page.get_by_role('button',name='Tela inicial',exact=True).click();page.get_by_role('button',name='LUTA RÁPIDA',exact=True).click();page.wait_for_timeout(1500)
 record('Combate abre com seis ações e Canvas',page.locator('[aria-label="Combate de gladiadores"]').count()==1 and page.locator('button[data-action]').count()==6)
 page.screenshot(path=str(ROOT/'dist/pc-battle-start.png'))
 # Move toward enemy, use keyboard attacks. No script manipulates engine state.
 page.keyboard.down('KeyD');page.wait_for_timeout(800);page.keyboard.up('KeyD')
 before_hp=page.get_by_role('progressbar',name='Vida do rival',exact=True).get_attribute('aria-valuenow')
 for i in range(6):
  page.keyboard.press('KeyJ');page.wait_for_timeout(300)
 after_hp=page.get_by_role('progressbar',name='Vida do rival',exact=True).get_attribute('aria-valuenow')
 record('Teclado J causa dano com arma animada',int(after_hp)<int(before_hp),{'before':before_hp,'after':after_hp})
 page.screenshot(path=str(ROOT/'dist/pc-battle.png'))
 page.keyboard.press('Escape');page.wait_for_timeout(150)
 record('Esc abre pausa',page.get_by_text('Combate pausado',exact=True).count()==1)
 time0=page.locator('div[class*="ArenaBattle_module_css_middle"] b').inner_text();page.wait_for_timeout(600);time1=page.locator('div[class*="ArenaBattle_module_css_middle"] b').inner_text()
 record('Pausa preserva tempo',time0==time1)
 page.screenshot(path=str(ROOT/'dist/pc-paused.png'))
 page.get_by_role('button',name='CONTINUAR',exact=True).click();page.keyboard.press('KeyW');page.wait_for_timeout(100);page.keyboard.press('Space');page.wait_for_timeout(100);page.keyboard.down('Shift');page.wait_for_timeout(300);page.keyboard.up('Shift')
 page.keyboard.press('Escape');page.get_by_role('button',name='ABANDONAR DUELO',exact=True).click();page.wait_for_timeout(200)
 record('Abandonar limpa combate e volta à cidade',page.locator('main[data-screen=camp]').count()==1 and page.locator('[aria-label="Combate de gladiadores"]').count()==0)
 # Actual UI persisted in test storage after finishing flow.
 old=page.evaluate("localStorage.getItem('arena-save-v5')")
 page.set_content(HTML,wait_until='load');page.wait_for_timeout(400)
 record('Reabertura mantém save no storage do teste',page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5')).character.name")=='Thiago — Arena')
 record('Nenhuma solicitação externa',len(requests)==0,requests)
 record('Nenhum erro JavaScript',len(errors)==0,errors)
 browser.close()
 (ROOT/'dist/browser-test-report.json').write_text(json.dumps({'browser':'Chromium','mode':'Headless, actual inline HTML; about:blank, offline; localStorage test double due to managed URL policy','tests':reports,'passed':sum(x['passed'] for x in reports),'failed':sum(not x['passed'] for x in reports),'errors':errors,'networkRequests':requests},indent=2,ensure_ascii=False))
