from pathlib import Path
import json, re, sys
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
HTML=(ROOT/'dist/ARENA_FILHOS_DA_AREIA_PC.html').read_text()
OUT=ROOT/'dist';results=[]
def check(name,passed,detail=None):
 results.append({'name':name,'passed':bool(passed),'detail':detail})
 print(name, bool(passed), str(detail)[:120] if detail is not None else '',flush=True)
 if not passed:raise AssertionError(name)
STORE="""(initial)=>{const store=initial||{};Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=String(v),removeItem:k=>delete store[k],clear:()=>Object.keys(store).forEach(k=>delete store[k])}});window.__testStorage=store;}"""
with sync_playwright() as pw:
 browser=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
 ctx=browser.new_context(viewport={'width':1366,'height':920},accept_downloads=True)
 ctx.set_offline(True);ctx.route('**/*',lambda route:route.abort())
 page=ctx.new_page();errors=[];requests=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.on('request',lambda r:requests.append(r.url) if r.url.startswith(('http:','https:')) else None)
 mode='file://'
 try:page.goto((OUT/'ARENA_FILHOS_DA_AREIA_PC.html').as_uri(),wait_until='load',timeout=4000)
 except Exception as ex:
  mode='actual HTML in about:blank, offline, localStorage test double (managed URL restriction)'
  print('Navigation fallback:',str(ex)[:140],flush=True)
  page.close();page=ctx.new_page()
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.on('request',lambda r:requests.append(r.url) if r.url.startswith(('http:','https:')) else None)
  page.evaluate(STORE,{})
  page.set_content(HTML,wait_until='load')
 page.set_default_timeout(8000);page.wait_for_timeout(700)
 try:
  check('Boot da expansão 5.0 etapa 1',page.locator('main[data-version="5.0.0-alpha.1"]').count()==1)
  check('Capa original intacta',page.locator('img').first.evaluate('(i)=>i.complete&&i.naturalWidth>500'))
  page.screenshot(path=str(OUT/'stage1-home.png'))
  page.get_by_role('button',name='ENTRAR NO LUDUS',exact=True).click();page.wait_for_timeout(350)
  check('Cidade e nova entrada coexistem',page.get_by_role('button',name='FORJA',exact=True).count()==1 and page.get_by_role('button',name='Abrir Santuário Interior').count()==1)
  page.screenshot(path=str(OUT/'stage1-city.png'))
  before=page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5'))")
  page.get_by_role('button',name='Cultivo',exact=True).click();page.wait_for_timeout(650)
  check('Núcleo inicialmente velado',page.locator('[data-awakened="false"]').count()==1)
  check('Gladiador real desenhado no santuário',page.locator('canvas').first.evaluate("c=>{let d=c.getContext('2d').getImageData(c.width/2,c.height/2,1,1).data;return d[3]>0}"))
  page.screenshot(path=str(OUT/'stage1-dormant.png'))
  page.get_by_role('button',name='DESPERTAR MEU NÚCLEO').click()
  check('Despertar exige confirmação',page.get_by_role('button',name='CONFIRMAR DESPERTAR').count()==1)
  page.get_by_role('button',name='Ainda não').click()
  check('Cancelar não desperta nem gasta recursos',page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5')).cultivation.core.awakenedAt") is None)
  page.get_by_role('button',name='DESPERTAR MEU NÚCLEO').click();page.get_by_role('button',name='CONFIRMAR DESPERTAR').click();page.wait_for_timeout(2500)
  after=page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5'))")
  check('Despertar vincula permanentemente o mesmo núcleo',after['cultivation']['core']['id']==before['cultivation']['core']['id'] and after['cultivation']['core']['awakenedAt'] is not None)
  check('Personagem e economia preservados no despertar',after['character']==before['character'])
  check('Reino e estrela iniciais consistentes',after['cultivation']['realm']=='Desperto' and after['cultivation']['star']==1)
  check('Não existe botão de novo sorteio',page.get_by_role('button',name='DESPERTAR MEU NÚCLEO').count()==0)
  page.screenshot(path=str(OUT/'stage1-awakened.png'))
  core=after['cultivation']['core']
  check('Ficha revela todos os componentes',all(v in page.locator('body').inner_text() for v in [core['nature'],core['archetype'],core['aspect'],core['innate']]))
  page.get_by_role('tab',name='Meridianos',exact=True).click();page.wait_for_timeout(150)
  check('Atlas contém os doze meridianos',page.get_by_role('tabpanel').locator('[data-meridian-id]').count()==12)
  check('Comandos da etapa 2 não foram falsamente habilitados',page.get_by_role('button',name=re.compile('MEDITAR|ROMPER REINO')).count()==0)
  page.screenshot(path=str(OUT/'stage1-meridians.png'))
  page.get_by_role('tab',name='Jornada',exact=True).click()
  check('Roteiro in-game com dez entregas',page.get_by_role('tabpanel').locator('article').count()==10)
  page.screenshot(path=str(OUT/'stage1-roadmap.png'))
  page.get_by_role('button',name='Voltar ao ludus',exact=True).click()
  page.get_by_role('button',name='PERSONALIZAR',exact=False).first.click()
  page.get_by_role('textbox').first.fill('Thiago — Desperto');page.wait_for_timeout(100)
  check('Renomear preserva o núcleo',page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5')).cultivation.core.id")==core['id'])
  page.get_by_role('button',name='Voltar ao ludus',exact=True).click();page.get_by_role('button',name='FORJA',exact=True).click();page.wait_for_timeout(300)
  article=page.locator('article').filter(has_text='Dente de chacal').first
  article.get_by_role('button',name=re.compile('COMPRAR')).click();page.wait_for_timeout(120)
  got=page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5'))")
  check('Loja compra e equipa sem apagar cultivo',got['character']['equipped']['weapon']=='dagger-1' and got['cultivation']['core']==core)
  page.get_by_role('button',name='Treinar',exact=True).click();page.get_by_role('button',name='Melhorar Força',exact=True).click();page.wait_for_timeout(100)
  check('Treino marcial preserva núcleo desperto',page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5')).cultivation.core.awakenedAt")==core['awakenedAt'])
  page.get_by_role('button',name='Arenas',exact=True).click();page.wait_for_timeout(200)
  check('Mapa e três arenas seguem disponíveis','Anfiteatro Solar' in page.locator('body').inner_text())
  page.get_by_role('button',name='Ajuda e configurações').click()
  with page.expect_download() as download:page.get_by_role('button',name='EXPORTAR',exact=True).click()
  download.value.save_as(str(OUT/'browser-stage1-save.json'))
  exported=json.loads((OUT/'browser-stage1-save.json').read_text());code=page.get_by_role('textbox',name='Código de recuperação').input_value()
  check('Backup ARENA5 inclui a identidade desperta',exported['cultivation']['core']==core and code.startswith('ARENA5:'))
  page.get_by_role('button',name='IMPORTAR CÓDIGO',exact=True).click();page.get_by_role('button',name='CONFIRMAR IMPORTAÇÃO',exact=True).click();page.wait_for_timeout(100)
  page.get_by_role('button',name='Cultivo',exact=True).click()
  check('Importação reabre núcleo sem outro despertar',page.locator('[data-awakened="true"]').count()==1 and page.get_by_role('button',name='DESPERTAR MEU NÚCLEO').count()==0)
  page.get_by_role('button',name='Tela inicial',exact=True).click();page.get_by_role('button',name='LUTA RÁPIDA',exact=True).click();page.wait_for_timeout(1500)
  check('Combate original com seis ações',page.locator('button[data-action]').count()==6)
  page.keyboard.down('KeyD');page.wait_for_timeout(1100);page.keyboard.up('KeyD')
  rival0=int(page.get_by_role('progressbar',name='Vida do rival',exact=True).get_attribute('aria-valuenow'))
  for _ in range(7):page.keyboard.press('KeyJ');page.wait_for_timeout(290)
  rival1=int(page.get_by_role('progressbar',name='Vida do rival',exact=True).get_attribute('aria-valuenow'))
  check('Teclado causa dano no combate real',rival1<rival0,{'before':rival0,'after':rival1})
  page.screenshot(path=str(OUT/'stage1-battle.png'))
  page.keyboard.press('Escape');page.wait_for_timeout(100)
  check('Esc pausa o combate',page.get_by_text('Combate pausado',exact=True).count()==1)
  hp=page.get_by_role('progressbar',name='Sua vida',exact=True).get_attribute('aria-valuenow');page.wait_for_timeout(400)
  check('Pausa congela combate',page.get_by_role('progressbar',name='Sua vida',exact=True).get_attribute('aria-valuenow')==hp)
  page.get_by_role('button',name='ABANDONAR DUELO',exact=True).click();page.wait_for_timeout(100)
  check('Sair do combate mantém núcleo',page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5')).cultivation.core.id")==core['id'])
  # Reload actual HTML while preserving test origin storage if file navigation is restricted.
  data=page.evaluate("(()=>{let o={};for(let k of ['arena-save-v5','arena-save-v3','arena-save-v5-before-stage-1']){let v=localStorage.getItem(k);if(v)o[k]=v;}return o;})()")
  page.close();page=ctx.new_page();page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda r:requests.append(r.url) if r.url.startswith(('http:','https:')) else None)
  if mode=='file://':page.goto((OUT/'ARENA_FILHOS_DA_AREIA_PC.html').as_uri(),wait_until='load')
  else:page.evaluate(STORE,data);page.set_content(HTML,wait_until='load')
  page.wait_for_timeout(400);page.get_by_role('button',name='ENTRAR NO LUDUS',exact=True).click();page.get_by_role('button',name='Cultivo',exact=True).click();page.wait_for_timeout(200)
  reloaded=page.evaluate("JSON.parse(localStorage.getItem('arena-save-v5'))")
  check('Reabertura mantém nome, arma e núcleo',reloaded['character']['name']=='Thiago — Desperto' and reloaded['character']['equipped']['weapon']=='dagger-1' and reloaded['cultivation']['core']==core)
  check('Checkpoint v5 anterior foi preservado',page.evaluate("localStorage.getItem('arena-save-v5-before-stage-1')!==null"))
  for width,height in [(1366,768),(390,844),(844,390),(320,568)]:
   page.set_viewport_size({'width':width,'height':height});page.get_by_role('tab',name='Núcleo',exact=True).click();page.wait_for_timeout(220)
   metrics=page.evaluate("({body:document.body.scrollWidth,w:innerWidth,content:Array.from(document.querySelectorAll('[class*=ArenaCultivation_module_css]')).filter(e=>e.offsetWidth&&e.scrollWidth>e.clientWidth+3).map(e=>({c:e.className,w:e.clientWidth,s:e.scrollWidth}))})")
   check(f'Layout sem rolagem horizontal {width}x{height}',metrics['body']<=width+1 and not metrics['content'],metrics)
   page.get_by_role('tab',name='Meridianos',exact=True).click();page.wait_for_timeout(50)
   check(f'Atlas legível {width}x{height}',page.get_by_role('img',name=re.compile('Rede espiritual')).is_visible())
   page.screenshot(path=str(OUT/f'stage1-{width}x{height}.png'))
  check('Sem solicitações HTTP de jogo',not requests,requests)
  check('Sem erros JavaScript',not errors,errors)
 except Exception as e:
  if not results or results[-1]['passed']:results.append({'name':'Browser exception','passed':False,'detail':str(e)})
  print('FAILED',str(e),flush=True);page.screenshot(path=str(OUT/'stage1-failure.png'))
 finally:
  report={'mode':mode,'browser':'Chromium headless','passed':sum(t['passed'] for t in results),'failed':sum(not t['passed'] for t in results),'tests':results,'errors':errors,'networkRequests':requests}
  (OUT/'stage1-browser-report.json').write_text(json.dumps(report,indent=2,ensure_ascii=False));browser.close()
  if report['failed']:sys.exit(1)
