'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {Save:V,Expansion:X,Cultivation:C,Adapter:A,D,Beasts:B,Species:SPEC,WildWorld:W,WildRegions:REG,WildCombatEngine:E,WildRig:G}=require('../dist/core-test.cjs');
const results=[],memory=new Map();global.localStorage={getItem:k=>memory.has(k)?memory.get(k):null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k),clear:()=>memory.clear()};
const clone=x=>JSON.parse(JSON.stringify(x)),now=100000;
function test(name,fn){memory.clear();try{fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.stack});}}
function fresh(seed='stage4'){let r=X.awaken(V.fresh(1000,seed),2000);r.character.gold=400;r.cultivation.essence=250;return r;}
function setup(species){const start=fresh();const {save,ticket}=W.open(start,'bosque',now);if(species){ticket.species=species;ticket.individual={...B.generate(species,'wild-test',now),id:ticket.individual.id,origin:'wild',bonded:false};}const e=new E(save,ticket);e.martial.intro=0;return{start,save,ticket,e};}
function advance(e,seconds){for(let i=0;i<seconds*120;i++)e.step(1/120);}
function weaken(e){e.aiEnabled=false;e.actor.hp=e.actor.maxHp*.3;e.actor.will=45;e.actor.x=680;e.player.x=500;}
function sealPerfect(e){for(let i=0;i<3;i++){e.needleTime=0;assert.equal(e.seal(),true);}}
function captured(){const x=setup();weaken(x.e);x.e.command('subdue');sealPerfect(x.e);return {...x,result:x.e.resolution()};}
function stateFixture(count=6){let s=fresh();s.world.exploration={...W.empty(),serial:count,successes:count};return s;}

test('Etapa 4 e versão registradas',()=>{assert.equal(X.stage,4);assert.equal(X.version,'5.0.0-alpha.4');});
test('Quatro rotas com oito espécies catalogadas',()=>{assert.equal(REG.length,4);assert.equal(new Set(REG.flatMap(r=>r.species.map(s=>s.id))).size,8);for(const r of REG)for(const s of r.species)assert.ok(B.species(s.id)&&s.weight>0);});
test('Quatro paisagens e faixas de perigo diferentes',()=>{assert.equal(new Set(REG.map(r=>r.landscape)).size,4);assert.deepEqual(REG.map(r=>r.danger),[1,2,3,4]);});
test('Expedições começam bloqueadas na dormência',()=>assert.throws(()=>W.open(V.fresh(),'bosque',now),/Desperte/));
test('Primeiro habitat abre ao despertar',()=>{const s=fresh();assert.equal(W.available(s,'bosque'),true);assert.equal(W.available(s,'rubras'),false);});
test('Requisitos progressivos 2, 4 e 6 sucessos',()=>{for(const r of REG.slice(1)){let s=stateFixture(r.minimum-1);assert.equal(W.available(s,r.id),false);s.world.exploration.successes++;s.world.exploration.serial++;assert.equal(W.available(s,r.id),true);}});
test('Campanha antiga libera rotas sem apagar progresso',()=>{for(const r of REG.slice(1)){let s=fresh();s.world.clearedArenaEncounters=[r.arenaUnlock];assert.equal(W.available(s,r.id),true);}});
test('Região desconhecida é rejeitada',()=>assert.throws(()=>W.open(fresh(),'none',now),/desconhecida/));
test('Relógio inválido não cria ticket',()=>{for(const n of [-1,NaN,Infinity,1.4])assert.throws(()=>W.open(fresh(),'bosque',n),/Relógio/);});
test('Ticket é imutável no save anterior',()=>{const s=fresh(),before=JSON.stringify(s);W.open(s,'bosque',now);assert.equal(JSON.stringify(s),before);});
test('Avistar registra espécie sem conceder animal',()=>{const {save,ticket}=setup();assert.ok(save.beasts.discoveredSpecies.includes(ticket.species));assert.equal(save.beasts.collection.length,0);});
test('Abrir não cobra ouro nem essência',()=>{const {start,save}=setup();assert.deepEqual(save.character,start.character);assert.deepEqual(save.cultivation,start.cultivation);});
test('Indivíduo selvagem é gerado antes do pacto',()=>{const {ticket}=setup();assert.equal(ticket.individual.origin,'wild');assert.equal(ticket.individual.bonded,false);assert.equal(ticket.individual.level,ticket.level);assert.equal(ticket.individual.mastery,0);});
test('Recarregar não gera candidato novo',()=>{const s=fresh(),a=W.open(s,'bosque',now).ticket,b=W.open(s,'bosque',now+5000).ticket;for(const k of ['species','level','id'])assert.equal(a[k],b[k]);for(const k of ['id','potential','bloodline','seed'])assert.deepEqual(a.individual[k],b.individual[k]);});
test('Renomear gladiador não muda rolagem do próximo encontro',()=>{let s=fresh(),a=W.open(s,'bosque',now).ticket;s.character.name='Outro';let b=W.open(s,'bosque',now).ticket;assert.deepEqual(a,b);});
test('Uma única expedição pode ficar pendente',()=>{const {save}=setup();assert.throws(()=>W.open(save,'bosque',now),/pendente/);});
test('Capacidade do santuário é respeitada antes da saída',()=>{const s=fresh();s.beasts.collection=Array.from({length:128},(_,i)=>B.generate('pyrofang','f'+i,now));assert.throws(()=>W.open(s,'bosque',now),/completo/);});
test('128 encontros diferentes preservam IDs únicos',()=>{let ids=new Set(),species=new Set();let s=stateFixture();for(let i=0;i<128;i++){let o=W.open(s,REG[i%4].id,now+i);ids.add(o.ticket.individual.id);species.add(o.ticket.species);o.save.world.exploration.pending=null;s=o.save;}assert.equal(ids.size,128);assert.equal(species.size,8);});
test('Ticket completa roundtrip em ARENA5',()=>{const {save}=setup();assert.deepEqual(V.decode(V.encode(save)).world.exploration,W.state(save));});
test('Save v3 migra sem receber captura gratuita',()=>{const old=D.fresh(),s=V.migrateV3(old);assert.equal(W.state(s).successes,0);assert.equal(s.beasts.collection.length,0);assert.deepEqual(A.toLegacy(s),old);});
test('Checkpoint da etapa 3 é preservado antes da etapa 4',()=>{const raw=JSON.stringify(fresh());localStorage.setItem(V.KEY,raw);V.load();assert.equal(localStorage.getItem(V.STAGE4_BACKUP_KEY),raw);V.persist(fresh('different'));V.load();assert.equal(localStorage.getItem(V.STAGE4_BACKUP_KEY),raw);});
test('Atualizar checkpoint não altera moedas ou linhagem',()=>{const {save,ticket,e}=setup();e.player.hp=80;const out=W.update(save,ticket.id,e.checkpoint());assert.equal(out.world.exploration.pending.checkpoint.player.hp,80);assert.deepEqual(out.character,save.character);assert.deepEqual(out.world.exploration.pending.individual,ticket.individual);});
test('Checkpoint de ticket alheio é rejeitado',()=>{const {save,e}=setup();assert.throws(()=>W.update(save,'wrong',e.checkpoint()),/expirada/);});
test('Save inválido não conserva região ou espécie forjada',()=>{let {save}=setup();save.world.exploration.pending.species='wrong';assert.equal(V.validate(save).world.exploration.pending,null);});
test('Validação limita vida, vontade, contadores e pulsos',()=>{const {save,ticket,e}=setup();let cp=e.checkpoint();cp.player.hp=Infinity;cp.beast.will=-999;cp.seals=[500,-9,Infinity,2,3];cp.rejections=999;cp.elapsed=-8;save.world.exploration.pending.checkpoint=cp;const clean=V.validate(save).world.exploration.pending.checkpoint;assert.ok(Number.isFinite(clean.player.hp));assert.equal(clean.beast.will,0);assert.deepEqual(clean.seals,[100,0,0]);assert.equal(clean.rejections,3);assert.equal(clean.elapsed,0);});
test('Histórico evita IDs repetidos e fica limitado a 16',()=>{const x=W.validate({serial:50,history:Array.from({length:30},(_,i)=>({id:'a'+i,region:'bosque',species:'pyrofang',outcome:'captured',name:'P',at:1}))});assert.equal(x.history.length,16);assert.equal(x.history[0].id,'a14');});

test('Composição preserva atributos marciais',()=>{const {start,e}=setup();assert.equal(e.player.power,D.stats(A.toLegacy(start)).power);assert.equal(e.player.maxHp,D.stats(A.toLegacy(start)).hp);});
test('Mover é contínuo e não causa dano à distância',()=>{const {e}=setup();e.aiEnabled=false;e.actor.x=1100;const hp=e.actor.hp;e.input.move=1;advance(e,.4);assert.ok(e.player.x>470);e.command('light');advance(e,1);assert.equal(e.actor.hp,hp);});
test('Ataque sem vigor não inicia',()=>{const {e}=setup();e.player.stamina=0;assert.equal(e.command('heavy'),false);assert.equal(e.player.state,'idle');});
test('Primeiro quadro de preparo não causa dano',()=>{const {e}=setup('pyrofang');e.aiEnabled=false;e.player.x=500;e.actor.x=620;e.command('light');advance(e,.08);assert.equal(e.actor.hp,e.actor.maxHp);});
for(const s of SPEC)test(s.name+': lâmina atinge anatomia real',()=>{let found=false;for(let gap=80;gap<=180;gap+=10){const {e}=setup(s.id);e.aiEnabled=false;e.player.x=500;e.actor.x=500+gap;const h=e.actor.hp;e.command('light');advance(e,1);if(e.actor.hp<h){found=true;assert.equal(e.hits,1);break;}}assert.ok(found);});
for(const s of SPEC)test(s.name+': IA se aproxima e pode vencer jogador parado',()=>{const {e}=setup(s.id);advance(e,90);assert.equal(e.outcome,'lost');assert.equal(e.player.hp,0);});
test('Oito anatomias têm zonas distintas de corpo e cabeça',()=>{let shapes=SPEC.map(s=>{const {e}=setup(s.id);return JSON.stringify(G.zones(e.actor));});assert.equal(new Set(shapes).size,8);});
test('Pesado reduz mais vontade e causa mais dano',()=>{const a=setup('pyrofang').e,b=setup('pyrofang').e;for(const e of [a,b]){e.aiEnabled=false;e.player.x=500;e.actor.x=620;}a.command('light');b.command('heavy');advance(a,1.3);advance(b,1.3);assert.ok(b.actor.hp<a.actor.hp);assert.ok(b.actor.will<a.actor.will);});
test('Guarda mineral reduz dano leve',()=>{const {e}=setup('stoneback');e.aiEnabled=false;e.player.x=500;e.actor.x=630;e.actor.state='guard';e.actor.duration=9;e.command('light');advance(e,1);assert.ok(e.damage<10&&e.damage>0);});
test('Foco consome 18 vigor, reduz vontade sem ferir',()=>{const {e}=setup();e.aiEnabled=false;e.actor.x=e.player.x+210;const hp=e.actor.hp;assert.equal(e.command('focus'),true);assert.equal(e.player.stamina,e.player.maxStamina-18);advance(e,1.3);assert.equal(e.actor.hp,hp);assert.equal(e.actor.will,77);});
test('Foco distante não consome vigor',()=>{const {e}=setup();e.actor.x=1100;assert.equal(e.command('focus'),false);assert.equal(e.player.stamina,e.player.maxStamina);});
test('Foco tem recarga e não permite spam',()=>{const {e}=setup();e.aiEnabled=false;e.actor.x=e.player.x+210;e.command('focus');advance(e,1.2);assert.equal(e.command('focus'),false);});
test('Dano interrompe canalização',()=>{const {e}=setup('pyrofang');e.actor.x=e.player.x+195;e.actor.state='windup';e.actor.elapsed=.69;e.actor.duration=.72;e.command('focus');advance(e,.7);assert.ok(e.player.hp<e.player.maxHp);assert.equal(e.willFocus,0);});
test('Salto tem altura real e aterrissa',()=>{const {e}=setup();e.aiEnabled=false;assert.equal(e.command('jump'),true);advance(e,.2);assert.ok(e.player.y<-25);advance(e,1);assert.equal(e.player.y,0);});
test('Esquiva move e torna jogador invulnerável',()=>{const {e}=setup();const x=e.player.x;assert.equal(e.command('dodge'),true);advance(e,.08);assert.ok(e.player.x<x-10);assert.ok(e.player.invuln>0);});
test('Fúria usa barra da arena, não poderes de feras',()=>{const {e}=setup();assert.equal(e.command('special'),false);e.player.rage=100;assert.equal(e.command('special'),true);assert.equal(e.player.rage,0);});
test('Pausa congela animais, gladiador e projéteis',()=>{const {e}=setup('mistwyrm');advance(e,4);e.input.move=1;e.setPaused(true);let cp=e.checkpoint(),clock=e.clock;advance(e,5);assert.deepEqual(e.checkpoint(),cp);assert.equal(e.clock,clock);assert.equal(e.input.move,0);});
test('Besta invulnerável fictícia nunca produz dano automático',()=>{const {e}=setup();e.aiEnabled=false;e.actor.x=1180;e.player.x=75;advance(e,10);assert.equal(e.player.hp,e.player.maxHp);assert.equal(e.actor.hp,e.actor.maxHp);});

test('Subjugação requer vida, vontade, distância e núcleo',()=>{const {e}=setup();assert.equal(e.command('subdue'),false);weaken(e);e.actor.will=61;assert.equal(e.command('subdue'),false);e.actor.will=30;e.actor.hp=e.actor.maxHp*.41;assert.equal(e.command('subdue'),false);e.actor.hp=e.actor.maxHp*.3;e.actor.x=1000;assert.equal(e.command('subdue'),false);e.actor.x=680;assert.equal(e.command('subdue'),true);});
test('Zerar vida derrota e não captura',()=>{const {e}=setup('pyrofang');e.aiEnabled=false;e.actor.x=610;e.player.x=500;e.actor.hp=1;e.command('heavy');advance(e,2);assert.equal(e.outcome,'defeated');assert.equal(e.command('subdue'),false);});
test('Física para durante confronto espiritual',()=>{const {e}=setup();weaken(e);e.command('subdue');const x=e.player.x,ax=e.actor.x,hp=e.player.hp;e.input.move=1;advance(e,2);assert.equal(e.player.x,x);assert.equal(e.actor.x,ax);assert.equal(e.player.hp,hp);assert.notEqual(e.needle,50);});
test('Três pulsos centrais firmam pacto sem aleatoriedade',()=>{const {e}=setup();weaken(e);e.command('subdue');sealPerfect(e);assert.equal(e.phase,'resolved');assert.equal(e.outcome,'captured');assert.deepEqual(e.seals,[100,100,100]);});
test('Pausa também congela agulha',()=>{const {e}=setup();weaken(e);e.command('subdue');advance(e,.7);e.setPaused(true);const n=e.needle;advance(e,2);assert.equal(e.needle,n);assert.equal(e.seal(),false);});
test('Precisão e compatibilidade têm efeitos separados',()=>{const {e}=setup();weaken(e);const s=B.species(e.actor.species);e.rootSave.cultivation.core.nature=s.nature;e.rootSave.cultivation.core.archetype=s.archetype;assert.equal(e.captureBonus,20);});
test('Dez segundos sem selar contabiliza erro',()=>{const {e}=setup();weaken(e);e.command('subdue');advance(e,10.1);assert.deepEqual(e.seals,[0]);});
test('Falha retoma combate e aumenta vontade, sem recompensa',()=>{const {e}=setup();weaken(e);e.command('subdue');for(let i=0;i<3;i++){e.needleTime=Math.PI/2/(3.4+e.ticket.level*.06);e.seal();}assert.equal(e.phase,'combat');assert.equal(e.rejections,1);assert.equal(e.actor.will,67);assert.equal(e.resolution(),null);});
test('Terceira rejeição faz a fera escapar',()=>{const {e}=setup();for(let k=0;k<3;k++){weaken(e);e.command('subdue');for(let i=0;i<3;i++){e.needleTime=Math.PI/2/(3.4+e.ticket.level*.06);e.seal();}}assert.equal(e.outcome,'escaped');assert.equal(e.rejections,3);});
test('Resultado terminal não muda com cliques repetidos',()=>{const {e}=captured(),cp=e.checkpoint();e.retreat();e.seal();e.command('heavy');advance(e,1);assert.equal(e.outcome,'captured');assert.equal(e.player.hp,cp.player.hp);});
test('Retirar-se não depende de vencer',()=>{const {e}=setup();e.retreat();assert.equal(e.outcome,'retreated');});
test('Retomar recupera vida, vontade e tentativas',()=>{const {save,ticket,e}=setup();e.player.hp=87;e.actor.hp=47;e.actor.will=39;e.rejections=1;const n=W.update(save,ticket.id,e.checkpoint());const resumed=new E(n,n.world.exploration.pending);assert.equal(resumed.player.hp,87);assert.equal(resumed.actor.hp,47);assert.equal(resumed.actor.will,39);assert.equal(resumed.rejections,1);});
test('Retomar preserva pulsos já selados',()=>{const {save,ticket,e}=setup();weaken(e);e.command('subdue');e.needleTime=0;e.seal();const s=W.update(save,ticket.id,e.checkpoint()),r=new E(s,s.world.exploration.pending);assert.equal(r.phase,'duel');assert.deepEqual(r.seals,[100]);});
test('Resultado pendente pode ser registrado após fechar',()=>{const {save,ticket,e,result}=captured();let n=V.decode(V.encode(W.update(save,ticket.id,e.checkpoint()))),r=new E(n,n.world.exploration.pending);assert.equal(r.outcome,'captured');assert.ok(W.finish(n,r.resolution(),now+20).captured);});

test('Captura preserva potencial, linhagem, nível e seed do encontro',()=>{const {save,ticket,result}=captured(),out=W.finish(save,result,now+100);const b=out.save.beasts.collection[0];for(const k of ['id','potential','bloodline','level','seed','species'])assert.deepEqual(b[k],ticket.individual[k]);assert.equal(b.origin,'wild');assert.equal(b.bonded,true);assert.equal(b.mastery,0);});
test('Captura premia ouro e essência e encerra ticket',()=>{const {save,ticket,result}=captured(),out=W.finish(save,result,now+100),reward=W.rewards(ticket,'captured');assert.equal(out.save.character.gold,save.character.gold+reward.gold);assert.equal(out.save.cultivation.essence,save.cultivation.essence+reward.essence);assert.equal(out.save.world.exploration.pending,null);assert.equal(out.save.world.exploration.captures,1);assert.equal(out.save.world.exploration.successes,1);});
test('Registro duplicado não concede segunda captura/recompensa',()=>{const {save,result}=captured(),out=W.finish(save,result);assert.throws(()=>W.finish(out.save,result),/encerrada/);assert.equal(out.save.beasts.collection.length,1);});
test('Captura não avança arenas, talentos, nível ou assimilação',()=>{const {save,result}=captured(),out=W.finish(save,result).save;const a=clone(save.character),b=clone(out.character);a.gold=b.gold;assert.deepEqual(a,b);assert.deepEqual(out.assimilation,save.assimilation);assert.deepEqual(out.world.clearedArenaEncounters,save.world.clearedArenaEncounters);});
test('Linhagem dos companheiros anteriores não muda',()=>{const x=captured();x.save.beasts.collection=[B.generate('pyrofang','own',now)];const before=clone(x.save.beasts.collection[0]),out=W.finish(x.save,x.result).save;assert.deepEqual(out.beasts.collection[0],before);assert.equal(out.beasts.collection.length,2);});
test('Pacto forjado com vida alta não é aceito',()=>{const x=captured();x.result.checkpoint.beast.hp=x.e.actor.maxHp;assert.throws(()=>W.finish(x.save,x.result),/pacto/);});
test('Pacto forjado com vontade alta não é aceito',()=>{const x=captured();x.result.checkpoint.beast.will=100;assert.throws(()=>W.finish(x.save,x.result),/pacto/);});
test('Pulsos insuficientes ou fracos não concedem fera',()=>{for(const seals of [[100],[0,0,0]]){const x=captured();x.result.checkpoint.seals=seals;assert.throws(()=>W.finish(x.save,x.result),/pacto/);}});
test('Incoerência entre fase e resultado é rejeitada',()=>{const x=captured();x.result.checkpoint.phase='combat';assert.throws(()=>W.finish(x.save,x.result),/terminal/);});
test('Capacidade cheia durante o combate evita truncar coleção',()=>{const x=captured();x.save.beasts.collection=Array.from({length:128},(_,i)=>B.generate('stoneback','b'+i,now));assert.throws(()=>W.finish(x.save,x.result),/completo/);assert.equal(x.save.beasts.collection.length,128);});
for(const outcome of ['retreated','escaped','lost'])test(outcome+': sem perda de ouro nem recompensa',()=>{const {save,e}=setup();if(outcome==='retreated')e.retreat();else{e.phase='resolved';e.outcome=outcome;if(outcome==='lost')e.player.hp=0;}const out=W.finish(save,e.resolution()).save;assert.deepEqual(out.character,save.character);assert.deepEqual(out.cultivation,save.cultivation);assert.equal(out.world.exploration.successes,0);assert.equal(out.beasts.collection.length,0);});
test('Vitória sem captura conta rota e não cria indivíduo',()=>{const {save,e}=setup();e.actor.hp=0;e.phase='resolved';e.outcome='defeated';const out=W.finish(save,e.resolution()).save;assert.equal(out.beasts.collection.length,0);assert.equal(out.world.exploration.successes,1);assert.equal(out.world.exploration.defeats,1);});
test('Contabilização de captura não altera núcleo/meridianos',()=>{const {save,result}=captured(),out=W.finish(save,result).save;assert.deepEqual(out.cultivation.core,save.cultivation.core);assert.deepEqual(out.cultivation.meridians,save.cultivation.meridians);});
test('Validação e adaptação preservam expedição em andamento',()=>{const {save,ticket,e}=setup();let n=W.update(save,ticket.id,e.checkpoint());let legacy=A.toLegacy(n);legacy.gold+=12;let merged=V.validate(A.mergeLegacy(n,legacy));assert.deepEqual(merged.world.exploration.pending,n.world.exploration.pending);});
test('Arte original e motor da arena permanecem idênticos',()=>{const root=path.resolve(__dirname,'..'),baseline=JSON.parse(fs.readFileSync(path.join(root,'docs/preservation-baseline.json')));for(const [file,digest] of Object.entries(baseline))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex'),digest,file);});
test('HTML contém todos os módulos e proíbe chamadas externas',()=>{const text=fs.readFileSync(path.join(__dirname,'../dist/ARENA_FILHOS_DA_AREIA_PC.html'),'utf8');assert.ok(text.includes('Terras Selvagens'));assert.ok(text.includes('connect-src \'none\''));assert.ok(!/<script[^>]+src=/.test(text));assert.ok(!/fonts\.googleapis\.com/.test(text));});
const report={stage:4,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,tests:results};fs.writeFileSync(path.join(__dirname,'../dist/stage4-test-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;
