import React,{useEffect,useRef,useState} from 'react';
import {Helmet} from 'react-helmet';
import {Button} from '../components/Button';
import {Input} from '../components/Input';
import {ArenaPortrait} from '../components/ArenaPortrait';
import {ArenaCultivation} from '../components/ArenaCultivation';
import {ArenaExpansion} from '../helpers/ArenaExpansion';
import {CultivationEngine} from '../helpers/CultivationEngine';
import {ArenaBattle} from '../components/ArenaBattle';
import {ArenaItemIcon} from '../components/ArenaItemIcon';
import {ArenaSigil} from '../components/ArenaSigil';
import {ArenaArt as Art} from '../helpers/ArenaArt';
import {ArenaTypes as T} from '../helpers/ArenaTypes';
import {ArenaData as D} from '../helpers/ArenaData';
import {ArenaSaveV5} from '../helpers/ArenaSaveV5';
import {ArenaCharacterAdapter} from '../helpers/ArenaCharacterAdapter';
import {Swords,Shield,Crown,Coins,Flame,ArrowLeft,ArrowRight,Check,Lock,Settings,Download,Copy,Home,Map,ShoppingBag,User,BookOpen,Heart,Zap,Target,ChevronRight,Volume2,VolumeX,Award,Play,Compass} from 'lucide-react';
import styles from './_index.module.css';
type Screen='home'|'create'|'camp'|'map'|'gear'|'shop'|'train'|'help'|'reward'|'cultivation';
type RewardView=ReturnType<typeof D.reward>&{result:T.Result};
const slotNames:Record<T.Slot,string>={weapon:'Armas',helmet:'Elmos',armor:'Armaduras',shield:'Escudos'};
const statNames={power:'Força',vitality:'Vitalidade',endurance:'Resistência',agility:'Agilidade'};
const stylesAI:Record<T.Style,string>={balanced:'Equilibrado',aggressive:'Agressivo',guardian:'Defensivo',duelist:'Duelista',brute:'Brutamontes',lancer:'Lanceiro'};
export default function Index(){
 const [initial]=useState(()=>ArenaSaveV5.load());
 const initialLegacy=ArenaCharacterAdapter.toLegacy(initial.save);
 const [save,setSave]=useState<T.Save>(initialLegacy);const v5Ref=useRef(initial.save);
 const [cultivation,setCultivation]=useState(initial.save.cultivation);
 const [screen,setScreen]=useState<Screen>('home'),[notice,setNotice]=useState(initial.warning),[storageWarning,setStorageWarning]=useState('');
 const [slot,setSlot]=useState<T.Slot>('weapon'),[selected,setSelected]=useState(Math.min(11,initialLegacy.cleared.length)),[backup,setBackup]=useState('');
 const [battle,setBattle]=useState<{save:T.Save;id:number;practice:boolean;key:number}|null>(null),[reward,setReward]=useState<RewardView|null>(null);
 const [confirmImport,setConfirmImport]=useState(false);
 const next=D.encounters.find(e=>!save.cleared.includes(e.id))||D.encounters[11];
 const arena=Math.min(2,Math.floor(save.cleared.length/4));const stats=D.stats(save);
 useEffect(()=>{try{const merged=ArenaCharacterAdapter.mergeLegacy(v5Ref.current,save);v5Ref.current=merged;v5Ref.current=ArenaSaveV5.persist(merged);localStorage.setItem('arena-save-v3',JSON.stringify(save));setStorageWarning('');}catch{setStorageWarning('Salvamento local indisponível. Use Exportar backup antes de sair.');}},[save]);
 useEffect(()=>{if(!notice)return;const timer=window.setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(timer);},[notice]);
 function go(s:Screen){setScreen(s);setConfirmImport(false);}
 function fight(id:number,practice=false){if(!practice&&id>0&&!save.cleared.includes(id-1)){setNotice('Vença o duelo anterior para liberar este adversário.');return;}setBattle({save:D.clone(save),id,practice,key:Date.now()});}
 function finish(result:T.Result){const outcome=D.reward(save,result);setSave(outcome.save);setReward({...outcome,result});setBattle(null);setScreen('reward');}
 function buy(id:string){const purchased=D.purchase(save,id);if(!purchased){setNotice('Verifique o ouro e a categoria liberada.');return;}setSave(D.equip(purchased,id));setNotice(`${D.getItem(id).name}: comprado e equipado.`);}
 function equip(id:string){setSave(D.equip(save,id));setNotice(`${D.getItem(id).name} equipado.`);}
 function improve(key:keyof T.Save['stats']){if(save.points<1||save.stats[key]>=30)return;const s=D.clone(save);s.points--;s.stats[key]++;setSave(s);}
 function talent(key:keyof T.Save['talents']){if(save.points<2||save.talents[key]>=3)return;const s=D.clone(save);s.points-=2;s.talents[key]++;setSave(s);}
 function currentV5(){const merged=ArenaCharacterAdapter.mergeLegacy(v5Ref.current,save);v5Ref.current=merged;return merged;}
 function awakenCore(){
  const previous=currentV5(),next=ArenaExpansion.awaken(previous);
  if(next===previous)return;
  v5Ref.current=next;setCultivation(next.cultivation);
  try{v5Ref.current=ArenaSaveV5.persist(next);setStorageWarning('');setNotice('Despertar concluído. Seu núcleo e seu progresso foram salvos.');}
  catch{setStorageWarning('Despertar mantido nesta sessão, mas o armazenamento não está disponível. Exporte um backup antes de fechar.');}
 }
 function exportSave(){const root=currentV5(),code=ArenaSaveV5.encode(root);setBackup(code);const blob=new Blob([JSON.stringify(root,null,2)],{type:'application/json'});const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='arena-save-v5.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);setNotice('Backup v5 exportado. O código também está disponível abaixo.');}
 async function copySave(){const code=ArenaSaveV5.encode(currentV5());setBackup(code);try{await navigator.clipboard.writeText(code);setNotice('Código ARENA5 de recuperação copiado.');}catch{setNotice('Selecione e copie o código no campo abaixo.');}}
 function importSave(){try{const data=ArenaSaveV5.decode(backup);v5Ref.current=ArenaSaveV5.persist(data);setCultivation(data.cultivation);setSave(ArenaCharacterAdapter.toLegacy(data));setConfirmImport(false);setNotice(data.meta.migratedFromVersion===3?'Backup ARENA3 migrado e recuperado no Save v5.':'Gladiador v5 recuperado com sucesso.');go('camp');}catch(e){setNotice(e instanceof Error?e.message:'Código de recuperação inválido.');}}
 const back=(title:string,subtitle?:string)=><div className={styles.pageHeading}><Button variant="ghost" className={styles.back} onClick={()=>go('camp')} aria-label="Voltar ao ludus"><ArrowLeft size={20}/></Button><div>{subtitle&&<span>{subtitle}</span>}<h1>{title}</h1></div></div>;
 const nav=[{id:'camp' as const,label:'Ludus',Icon:Home},{id:'map' as const,label:'Arenas',Icon:Map},{id:'gear' as const,label:'Equipar',Icon:Shield},{id:'shop' as const,label:'Ferreiro',Icon:ShoppingBag},{id:'train' as const,label:'Treinar',Icon:Flame},{id:'cultivation' as const,label:'Cultivo',Icon:Compass}];
 return <main className={styles.app} data-version={ArenaExpansion.version} data-expansion-stage="1" data-screen={screen}>
 <Helmet><title>ARENA — Filhos da Areia · O Despertar 5.0</title><meta name="description" content="Jogo ilustrado para PC. Expansão 5.0, etapa 1: O Despertar do Núcleo."/><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/><meta name="theme-color" content="#362318"/></Helmet>
 {battle?<ArenaBattle key={battle.key} save={battle.save} encounterId={battle.id} practice={battle.practice} onFinish={finish} onExit={()=>{setBattle(null);go('camp');}} onSound={value=>setSave(s=>({...s,sound:value}))}/>:
 <>
 {screen==='home'?<section className={styles.home}>
 <div className={styles.homeArt}><img src={Art.cover} alt="Dois campeões ilustrados diante do coliseu" fetchPriority="high"/><div className={styles.artShade}/><span className={styles.edition}>EXPANSÃO 5.0 · ETAPA 1/10</span><div className={styles.homeMotes} aria-hidden="true"/></div>
 <div className={styles.homeIntro}><div className={styles.flourish}><span/><Swords size={22}/><span/></div><p className={styles.eyebrow}>UMA NOVA LENDA AGUARDA</p><h1>ARENA</h1><h2>FILHOS DA AREIA</h2><p className={styles.homeLead}>A mesma arena. Uma nova essência.<br/>Desperte o poder que já vive em você.</p>
 <Button className={styles.goldButton} onClick={()=>{go('camp');setSelected(next.id);}}><Swords size={19}/>{save.wins?'CONTINUAR JORNADA':'ENTRAR NO LUDUS'}<ArrowRight size={18}/></Button>
 <div className={styles.homeSecondary}><Button variant="outline" onClick={()=>fight(0,true)}><Play size={16}/> LUTA RÁPIDA</Button><Button variant="ghost" onClick={()=>go('create')}><User size={16}/> PERSONALIZAR</Button></div>
 <Button variant="ghost" className={styles.homeHelp} onClick={()=>go('help')}><BookOpen size={14}/> Controles, arquivo local e backup</Button>
 <div className={styles.homeFoot}><span>3 ARENAS</span><i/><span>12 DUELOS</span><i/><span>COMBATE REAL</span></div></div>
 </section>:<>
 <header className={styles.top}><Button variant="ghost" className={styles.wordmark} onClick={()=>go('home')} aria-label="Tela inicial"><ArenaSigil size={46}/></Button><div className={styles.playerMeta}><strong>{save.name}</strong><small>NÍVEL {save.level} <span>·</span> {save.xp}/{save.level*90} XP</small><i className={styles.miniXp}><i style={{width:`${Math.min(100,save.xp/(save.level*90)*100)}%`}}/></i></div><div className={styles.gold}><Coins size={19}/>{save.gold.toLocaleString('pt-BR')}</div><Button variant="ghost" className={styles.settings} onClick={()=>go('help')} aria-label="Ajuda e configurações"><Settings size={19}/></Button></header>
 <div className={styles.content} key={screen}>
 {screen==='cultivation'&&<ArenaCultivation save={save} model={cultivation} onAwaken={awakenCore} onBack={()=>go('camp')} onBackup={()=>go('help')} storageWarning={storageWarning}/>}
 {screen==='camp'&&<section className={styles.camp}>
 <div className={styles.townMap}><img src={Art.town} alt="Velaria: coliseu, ferreiro, arsenal e pátio de treinamento"/><div className={styles.townTitle}><span>SEJA BEM-VINDO A</span><h2>Velaria</h2></div><Button className={`${styles.location} ${styles.locationArena}`} onClick={()=>go('map')}><Crown size={20}/><span>ARENAS</span></Button><Button className={`${styles.location} ${styles.locationForge}`} onClick={()=>go('shop')}><ShoppingBag size={18}/><span>FORJA</span></Button><Button className={`${styles.location} ${styles.locationGear}`} onClick={()=>go('gear')}><Shield size={18}/><span>ARSENAL</span></Button><Button className={`${styles.location} ${styles.locationTrain}`} onClick={()=>go('train')}><Target size={18}/><span>PÁTIO</span></Button><div className={styles.townHint}>Clique nos lugares para explorar</div></div>
 <Button className={styles.cultivationBanner} onClick={()=>go('cultivation')} aria-label="Abrir Santuário Interior"><span className={styles.cultivationBadge}><Compass size={30}/></span><span><small>EXPANSÃO 5.0 · O DESPERTAR</small><b>{CultivationEngine.isAwakened(cultivation)?cultivation.core.name:'Seu núcleo está pronto para despertar.'}</b><em>{CultivationEngine.isAwakened(cultivation)?`${cultivation.realm} ${'★'.repeat(cultivation.star)} · ${cultivation.core.nature} / ${cultivation.core.archetype}`:'Visite o Santuário Interior. Seu progresso marcial será preservado.'}</em></span><ChevronRight size={24}/></Button>
 <div className={styles.campHero}><div className={styles.campArt}><ArenaPortrait save={save} arena={arena}/></div><div className={styles.campText}><span className={styles.eyebrow}>SEU LUDUS</span><h1>{save.cleared.length===12?'O invicto.':'Da areia à glória.'}</h1><p>{save.cleared.length===12?'As três coroas são suas. Revisite as arenas e domine outras armas.':'Equipe seu gladiador. Leia o rival. Faça cada golpe contar.'}</p><div className={styles.medals}><span><Award size={16}/>{save.wins} vitórias</span><span><Crown size={16}/>{save.cleared.filter(id=>D.encounters[id].boss).length}/3 coroas</span></div><Button variant="outline" className={styles.customize} onClick={()=>go('create')}>PERSONALIZAR <ChevronRight size={14}/></Button></div></div>
 <div className={styles.nextFight}><div><span className={styles.eyebrow}>{save.cleared.length===12?'REVISITAR O CAMPEÃO':'PRÓXIMO DESAFIO'}</span><h2>{next.name}<small>{next.epithet}</small></h2><p>{D.arenas[next.arena].name}</p></div><Button className={styles.goldButton} onClick={()=>fight(next.id)}><Swords size={20}/> LUTAR</Button></div>
 <div className={styles.campStats}>{[{Icon:Heart,name:'VIDA',value:stats.hp},{Icon:Swords,name:'ATAQUE',value:stats.power},{Icon:Shield,name:'DEFESA',value:stats.defense},{Icon:Zap,name:'VIGOR',value:stats.stamina}].map(({Icon,name,value})=><div key={name}><Icon size={17}/><strong>{value}</strong><span>{name}</span></div>)}</div>
 {save.points>0&&<Button className={styles.pointsBanner} onClick={()=>go('train')}><Flame size={19}/><span><b>{save.points} pontos disponíveis</b>Desenvolva atributos e técnicas.</span><ChevronRight size={19}/></Button>}
 <div className={styles.campOptions}><Button variant="outline" onClick={()=>go('map')}><Map size={20}/><span>Campanha<small>12 oponentes · 3 campeões</small></span><ChevronRight size={17}/></Button><Button variant="outline" onClick={()=>fight(0,true)}><Target size={20}/><span>Treino livre<small>Sem perder ouro ou progresso</small></span><ChevronRight size={17}/></Button></div>
 </section>}
 {screen==='create'&&<section>{back('Seu gladiador','IDENTIDADE')}<div className={styles.customGrid}><div className={styles.customPreview}><ArenaPortrait save={save} arena={arena}/><span>SEU EQUIPAMENTO, NO CORPO</span></div><div className={styles.customFields}>
 <label className={styles.field}>Nome de arena<Input value={save.name} maxLength={18} onChange={e=>setSave(s=>({...s,name:e.target.value}))} placeholder="Nome do gladiador"/></label>
 <div className={styles.field}>Tom de pele<div className={styles.swatches}>{D.skins.map((c,i)=><Button key={c} aria-label={`Tom de pele ${i+1}`} className={`${styles.swatch} ${save.skin===i?styles.selectedSwatch:''}`} style={{background:c}} onClick={()=>setSave(s=>({...s,skin:i}))}>{save.skin===i&&<Check size={19}/>}</Button>)}</div></div>
 <div className={styles.field}>Cor da casa<div className={styles.swatches}>{D.banners.map((c,i)=><Button key={c} aria-label={`Cor da casa ${i+1}`} className={`${styles.swatch} ${save.banner===i?styles.selectedSwatch:''}`} style={{background:c}} onClick={()=>setSave(s=>({...s,banner:i}))}>{save.banner===i&&<Check size={19}/>}</Button>)}</div></div>
 <div className={styles.field}>Constituição<div className={styles.segment}>{['Atlética','Robusta'].map((s,i)=><Button key={s} variant="outline" className={save.build===i?styles.activeTab:''} onClick={()=>setSave(s=>({...s,build:i}))}>{s}</Button>)}</div></div>
 <p className={styles.hint}>A aparência não altera os atributos. Armas, elmos, armaduras e escudos equipados aparecem durante o combate.</p><Button className={styles.goldButton} onClick={()=>{setSave(s=>({...s,name:s.name.trim()||'Caius'}));go('camp');}}><Check size={18}/> PRONTO PARA A ARENA</Button>
 </div></div></section>}
 {screen==='map'&&<section>{back('As três coroas','CAMPANHA')}<div className={styles.campaignProgress}><div style={{width:`${save.cleared.length/12*100}%`}}/><span>{save.cleared.length}/12 duelos conquistados</span></div>
 <div className={styles.worldMap}><img src={Art.map} alt="Mapa ilustrado dos três reinos: Velaria, Forja e Anfiteatro Solar"/><div className={styles.mapHeading}>A jornada das três coroas</div>{D.arenas.map((a,ar)=>{const locked=ar>0&&!save.cleared.includes(ar*4-1);return <Button key={a.name} disabled={locked} aria-label={`Ver região ${a.name}`} className={`${styles.mapPin} ${styles['mapPin'+ar]} ${D.encounters[selected].arena===ar?styles.mapPinActive:''}`} onClick={()=>{setSelected(ar*4);document.getElementById('chapter-'+ar)?.scrollIntoView({behavior:save.reducedMotion?'auto':'smooth',block:'start'});}}>{locked?<Lock size={18}/>:<Crown size={21}/>}<span>{['VELARIA','A FORJA','O IMPÉRIO'][ar]}</span></Button>;})}</div>
 <div className={styles.arenaGroups}>{D.arenas.map((a,ar)=><div className={styles.arenaGroup} id={'chapter-'+ar} key={a.name} style={{'--chapter-scene':`url(${Art.arenas[ar]})`,'--chapter-color':Art.chapterColors[ar]} as React.CSSProperties}><div className={styles.arenaGroupHeading}><span>{a.tag}</span><h2>{a.name}</h2><p>{a.description}</p></div><div className={styles.opponents}>{D.encounters.filter(e=>e.arena===ar).map(e=>{const locked=e.id>0&&!save.cleared.includes(e.id-1),won=save.cleared.includes(e.id);return <Button variant="outline" key={e.id} className={`${styles.opponent} ${selected===e.id?styles.selectedOpponent:''} ${e.boss?styles.boss:''}`} disabled={locked} onClick={()=>setSelected(e.id)}><span className={styles.opponentNumber}>{locked?<Lock size={16}/>:won?<Check size={17}/>:e.boss?<Crown size={19}/>:String(e.id+1).padStart(2,'0')}</span><span><b>{e.name}</b><small>{e.epithet}</small></span><ChevronRight size={16}/></Button>;})}</div></div>)}</div>
 <div className={styles.duelCard}><div className={styles.duelPortrait}><ArenaPortrait save={save} enemyId={selected} arena={D.encounters[selected].arena}/></div><div className={styles.duelInfo}><span className={styles.eyebrow}>{stylesAI[D.encounters[selected].style]}</span><h2>{D.encounters[selected].name}</h2><p>{D.getItem(D.encounters[selected].weapon).name}<br/>{D.encounters[selected].hp} PV · {D.encounters[selected].boss?'Campeão':'Gladiador'}</p><span className={styles.rewardTag}><Coins size={14}/> {D.encounters[selected].reward} ouro <small>na primeira vitória</small></span><Button className={styles.goldButton} onClick={()=>fight(selected)}><Swords size={18}/> DESAFIAR</Button></div></div>
 </section>}
 {(screen==='gear'||screen==='shop')&&<section>{back(screen==='shop'?'A forja de Velaria':'Arsenal do gladiador',screen==='shop'?'FERREIRO':'EQUIPAMENTO')}
 {screen==='shop'&&<div className={styles.merchantScene}><img src={Art.forge} alt="Brontes, ferreiro de Velaria, diante da sua bigorna"/><div className={styles.npcDialogue}><span>BRONTES · O FERREIRO</span><p>“Uma boa lâmina não faz o campeão. Mas ajuda bastante!”</p></div></div>}
 <div className={styles.armoryTop}><div className={styles.armoryPortrait}><ArenaPortrait save={save} arena={arena}/><div className={styles.slotDock}>{(['helmet','weapon','armor','shield'] as T.Slot[]).map((s,i)=><Button key={s} aria-label={`Selecionar ${slotNames[s]}`} className={`${styles.gearSlot} ${slot===s?styles.gearSlotActive:''} ${styles['gearSlot'+i]}`} onClick={()=>setSlot(s)}><ArenaItemIcon item={D.getItem(save.equipped[s])} size={48}/><span>{slotNames[s]}</span></Button>)}</div></div><div className={styles.armorySummary}><span className={styles.eyebrow}>{screen==='shop'?'SEU EQUIPAMENTO ATUAL':'FORJADO PARA VENCER'}</span><h2>{save.name}</h2><div><Swords size={17}/> {stats.power} ataque <Shield size={17}/> {stats.defense} defesa</div><p>{screen==='shop'?'Comprar equipa a peça imediatamente. Apenas as peças equipadas contam.':'Toque em um encaixe ou escolha uma peça abaixo. O gladiador veste seu equipamento de verdade.'}</p><span className={styles.tierBadge}>CATEGORIA {Math.min(3,1+Math.floor(save.cleared.length/4))} LIBERADA</span></div></div>
 <div className={styles.tabs}>{(['weapon','helmet','armor','shield'] as T.Slot[]).map(s=><Button key={s} variant="ghost" className={slot===s?styles.activeTab:''} onClick={()=>setSlot(s)}>{slotNames[s]}</Button>)}</div>
 <div className={styles.itemGrid}>{D.items.filter(i=>i.slot===slot&&(screen==='shop'||save.owned.includes(i.id))).map(i=>{const owned=save.owned.includes(i.id),equipped=save.equipped[i.slot]===i.id,locked=i.tier>1+Math.floor(save.cleared.length/4);return <article key={i.id} data-tier={i.tier} className={`${styles.itemCard} ${equipped?styles.equippedCard:''}`}><div className={styles.itemTitle}><ArenaItemIcon item={i} size={76}/><div><span>{['','COMUM','VETERANO','CAMPEÃO'][i.tier]}</span><h3>{i.name}</h3></div>{equipped&&<Check className={styles.equippedTick} size={17}/>}</div><p>{i.description}</p><div className={styles.itemNumbers}>{i.slot==='weapon'?<><span>DANO <b>{i.damage}</b></span><span>ALCANCE <b>{i.reach}</b></span><span>RITMO <b>{i.speed.toFixed(2)}×</b></span></>:<span>DEFESA <b>+{i.defense}</b></span>}</div>
 <Button variant={equipped?'ghost':'outline'} className={styles.itemAction} disabled={equipped||(!owned&&(locked||save.gold<i.price))} onClick={()=>owned?equip(i.id):buy(i.id)}>{equipped?'EQUIPADO':owned?'EQUIPAR':locked?<><Lock size={13}/> VENÇA A ARENA {i.tier-1}</>:<><Coins size={14}/> {i.price} · COMPRAR</>}</Button></article>;})}</div>
 {screen==='gear'&&<Button className={styles.fullOutline} variant="outline" onClick={()=>go('shop')}><ShoppingBag size={17}/> VISITAR O FERREIRO</Button>}
 </section>}
 {screen==='train'&&<section>{back('O caminho do guerreiro','ATRIBUTOS E TÉCNICAS')}<div className={styles.merchantScene}><img src={Art.trainer} alt="O mestre de armas no pátio de treino do ludus"/><div className={styles.npcDialogue}><span>VETERANO · MESTRE DE ARMAS</span><p>“Na arena, uma boa defesa vale tanto quanto a sua espada.”</p></div></div><div className={styles.trainingIntro}><Flame size={33}/><div><b>{save.points} pontos disponíveis</b><p>Cada nível concede dois pontos. Atributos custam um; técnicas custam dois.</p></div></div><h2 className={styles.sectionTitle}>Atributos</h2><div className={styles.trainingGrid}>{(['power','vitality','endurance','agility'] as const).map(key=><article className={styles.trainingCard} key={key}><div><h3>{statNames[key]}</h3><p>{{power:'+2 de dano por ponto',vitality:'+14 de vida por ponto',endurance:'+9 de vigor por ponto',agility:'+4 de velocidade e +1,5% crítico'}[key]}</p></div><strong>{save.stats[key]}</strong><Button variant="outline" disabled={save.points<1||save.stats[key]>=30} onClick={()=>improve(key)} aria-label={`Melhorar ${statNames[key]}`}>+1</Button></article>)}</div>
 <h2 className={styles.sectionTitle}>Técnicas de arena</h2><div className={styles.talentGrid}>{[{key:'guard' as const,title:'Muralha',Icon:Shield,description:'+12 de postura e +25 ms na janela de aparo por grau.'},{key:'fury' as const,title:'Carrasco',Icon:Flame,description:'+3 de fúria por acerto e maior dano no especial por grau.'},{key:'precision' as const,title:'Duelista',Icon:Target,description:'+4% de crítico e −0,12 s de recarga da esquiva por grau.'}].map(({key,title,Icon,description})=><article className={styles.talentCard} key={key}><Icon size={26}/><h3>{title}</h3><div className={styles.ranks}>{[0,1,2].map(n=><i key={n} className={save.talents[key]>n?styles.filledRank:''}/>)}</div><p>{description}</p><Button variant="outline" disabled={save.points<2||save.talents[key]>=3} onClick={()=>talent(key)}>{save.talents[key]>=3?'DOMINADO':'APRENDER · 2 PT'}</Button></article>)}</div><Button className={styles.fullOutline} variant="outline" onClick={()=>fight(0,true)}><Target size={17}/> PRATICAR NO PÁTIO</Button>
 </section>}
 {screen==='reward'&&reward&&<section className={styles.rewardScreen}><div className={styles.victoryEmblem}><ArenaSigil size={132} crown={reward.result.win}/></div><span className={styles.eyebrow}>{reward.result.practice?'TREINO CONCLUÍDO':reward.result.win?'A MULTIDÃO GRITA SEU NOME':'A JORNADA CONTINUA'}</span><h1>{reward.result.win?'Vitória.':'Reagrupe-se.'}</h1><p>{reward.result.win?`${D.encounters[reward.result.encounter].name} foi derrotado.`:'Leia a preparação do golpe, recue para recuperar vigor e procure uma abertura.'}</p><div className={styles.rewardNumbers}><div><Coins size={20}/><b>+{reward.gold}</b><span>OURO</span></div><div><Flame size={20}/><b>+{reward.xp}</b><span>EXPERIÊNCIA</span></div><div><Target size={20}/><b>{reward.result.hits}</b><span>ACERTOS</span></div></div><div className={styles.battleReport}><span>{Math.floor(reward.result.time)} s de combate</span><span>{reward.result.damage} dano causado</span><span>{reward.result.parries} aparos</span></div>{reward.levels>0&&<div className={styles.levelUp}><Flame size={19}/> NÍVEL {save.level} · +{reward.levels*2} PONTOS</div>}{reward.loot&&<div className={styles.loot}><ArenaItemIcon item={D.getItem(reward.loot)} size={50}/><div><span>PRÊMIO DO CAMPEÃO</span><b>{D.getItem(reward.loot).name}</b></div><Button variant="outline" onClick={()=>equip(reward.loot)} disabled={save.equipped[D.getItem(reward.loot).slot]===reward.loot}>EQUIPAR</Button></div>}{save.cleared.length===12&&<div className={styles.levelUp}><Crown size={20}/> AS TRÊS COROAS SÃO SUAS</div>}<Button className={styles.goldButton} onClick={()=>fight(reward.result.win?next.id:reward.result.encounter,reward.result.practice)}><Swords size={18}/>{reward.result.win?'PRÓXIMO DUELO':'TENTAR NOVAMENTE'}</Button><Button variant="outline" className={styles.fullOutline} onClick={()=>go('camp')}>RETORNAR AO LUDUS</Button></section>}
 {screen==='help'&&<section>{back('Manual do gladiador','AJUDA E SALVAMENTO')}<div className={styles.helpGrid}><article className={styles.helpCard}><h2><Swords size={22}/> Domine o combate</h2><p><b>Movimento:</b> segure as setas. A arma só causa dano se alcançar o corpo do rival. A direção do personagem acompanha o adversário.</p><p><b>Leve:</b> toque novamente durante a segunda metade do golpe para encadear até três cortes. <b>Pesado:</b> mais lento, causa mais dano e pressão na guarda.</p><p><b>Escudo:</b> mantenha pressionado para bloquear. Erga-o imediatamente antes do impacto para aparar e abrir o rival. Segurar desde muito cedo apenas bloqueia.</p><p><b>Esquiva:</b> usa a direção pressionada; sem direção, recua. <b>Salto:</b> altera a altura e pode evitar golpes baixos. <b>Fúria:</b> carregada por impactos e bloqueios; libera um especial a 100%.</p><p><b>Armas:</b> espadas equilibram; adagas são rápidas e causam sangramento com o pesado; machados e martelos quebram postura; lanças dominam o alcance, mas perdem dano muito perto.</p><p><b>Teclado:</b> A/D ou setas, J leve, K pesado, L escudo, espaço esquiva, W salto, E fúria e Esc pausa.</p></article>
 <article className={styles.helpCard}><h2><Download size={22}/> Edição local para PC</h2><p>Abra <b>ARENA_FILHOS_DA_AREIA_PC.html</b> em um navegador atualizado. O jogo, os cenários e as bibliotecas estão incorporados neste arquivo; não é necessário servidor, instalação ou conta.</p><p>O progresso é salvo neste navegador quando o armazenamento local está disponível. O arquivo não busca automaticamente o progresso do endereço publicado. Importe um código ARENA5: ou ARENA3: para transferir seu gladiador.</p><p>Mantenha o arquivo na mesma pasta e exporte seu backup antes de renomeá-lo, movê-lo ou apagar dados do navegador. No PC, use preferencialmente Chrome, Edge ou Firefox.</p><p>A edição exporta o conteúdo jogável existente no Floot: campanha das três coroas e apresentação ilustrada. A fundação de cultivo 5.0 está no save; captura e transformações de PoketPets ainda não fazem parte deste projeto.</p></article>
 <article className={styles.helpCard}><h2><Settings size={22}/> Preferências</h2><Button variant="outline" className={styles.preference} onClick={()=>setSave(s=>({...s,sound:!s.sound}))}>{save.sound?<Volume2 size={18}/>:<VolumeX size={18}/>}Som {save.sound?'ligado':'desligado'}<span>Alterar</span></Button><Button variant="outline" className={styles.preference} onClick={()=>setSave(s=>({...s,reducedMotion:!s.reducedMotion}))}>Efeitos reduzidos: {save.reducedMotion?'sim':'não'}<span>Alterar</span></Button><p>O som só começa após interação no combate. Efeitos reduzidos retiram tremor de câmera, trilhas e parte das animações de fundo.</p></article>
 <article className={styles.helpCard}><h2><BookOpen size={22}/> Proteja seu progresso</h2><p>O núcleo desperto faz parte do <b>Save v5</b>. A atualização cria uma cópia local única chamada <b>arena-save-v5-before-stage-1</b>, quando há um v5 anterior. Não existe sincronização automática entre arquivos ou navegadores.</p><p>Exporte antes de apagar dados do navegador, trocar de aparelho ou mover o HTML. Importar substitui o gladiador atual pelo backup.</p><div className={styles.backupActions}><Button variant="outline" onClick={exportSave}><Download size={16}/> EXPORTAR</Button><Button variant="outline" onClick={copySave}><Copy size={16}/> COPIAR CÓDIGO</Button></div><label className={styles.field}>Código de recuperação<Input value={backup} onChange={e=>{setBackup(e.target.value);setConfirmImport(false);}} placeholder="ARENA5:… / ARENA3:… / JSON v5" aria-label="Código de recuperação"/></label>{confirmImport?<div className={styles.confirmImport}><p>Substituir o progresso atual por este backup?</p><Button onClick={importSave}>CONFIRMAR IMPORTAÇÃO</Button><Button variant="ghost" onClick={()=>setConfirmImport(false)}>Cancelar</Button></div>:<Button variant="outline" disabled={!backup.trim()} onClick={()=>{try{ArenaSaveV5.decode(backup);setConfirmImport(true);}catch{setNotice('Código inválido. Cole um backup completo ARENA5: ou ARENA3:.');}}}>IMPORTAR CÓDIGO</Button>}{storageWarning&&<p className={styles.storageWarning}>{storageWarning}</p>}</article>
 </div><div className={styles.buildInfo}>ARENA · FILHOS DA AREIA · v{D.version} · EDIÇÃO PC<br/>Edição Ilustrada: cenários pintados e gladiadores articulados.<br/>Expansão 5.0 · Etapa 1/10: O Despertar.<br/>Save v5 com migração automática de ARENA3.<br/>Meditação, feras, poderes e transformações são etapas futuras.<br/>Cópia portátil do projeto Floot; o domínio publicado não foi alterado.</div></section>}
 </div>
 {!['reward','create'].includes(screen)&&<nav className={styles.bottomNav} aria-label="Navegação principal">{nav.map(({id,label,Icon})=><Button variant="ghost" key={id} className={screen===id?styles.navActive:''} onClick={()=>go(id)}><Icon size={20}/><span>{label}</span>{id==='train'&&save.points>0&&<i/>}</Button>)}</nav>}
 </>}
 {(notice||storageWarning)&&<div className={styles.toast} role="status">{notice||storageWarning}<Button variant="ghost" aria-label="Fechar aviso" onClick={()=>{setNotice('');setStorageWarning('');}}>×</Button></div>}
 </>}
 </main>;
}
