import {ArenaTypes as T} from './ArenaTypes';
import {ArenaData as D} from './ArenaData';
import {ArenaEngine} from './ArenaEngine';
import {ArenaCharacter} from './ArenaCharacter';
import {ArenaArt as Art} from './ArenaArt';
const INK='#322119';const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));const mix=(a:number,b:number,t:number)=>a+(b-a)*t;
const hash=(n:number)=>{const a=Math.sin(n*127.1+311.7)*43758.5453;return a-Math.floor(a);};
export class ArenaRenderer{
 ctx:CanvasRenderingContext2D;w=390;h=400;dpr=1;camera=640;zoom=1;reduced=false;private character:ArenaCharacter;
 constructor(public canvas:HTMLCanvasElement){const c=canvas.getContext('2d',{alpha:false});if(!c)throw new Error('Canvas 2D indisponível neste navegador.');this.ctx=c;this.character=new ArenaCharacter(c);}
 resize(w:number,h:number){this.w=Math.max(1,w);this.h=Math.max(1,h);this.dpr=Math.min(typeof window==='undefined'?1:window.devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.round(this.w*this.dpr));this.canvas.height=Math.max(1,Math.round(this.h*this.dpr));this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);}
 private polygon(points:number[][],fill:string,stroke=INK,width=2){const c=this.ctx;c.beginPath();points.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.closePath();c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=width;c.lineJoin='round';c.stroke();}}
 private ellipse(x:number,y:number,rx:number,ry:number,fill:string,stroke='',width=2){const c=this.ctx;c.beginPath();c.ellipse(x,y,Math.max(0,rx),Math.max(0,ry),0,0,Math.PI*2);c.fillStyle=fill;c.fill();if(stroke){c.lineWidth=width;c.strokeStyle=stroke;c.stroke();}}
 private line(x:number,y:number,x2:number,y2:number,color:string,width=2){const c=this.ctx;c.beginPath();c.moveTo(x,y);c.lineTo(x2,y2);c.strokeStyle=color;c.lineWidth=width;c.lineCap='round';c.stroke();}
 private gradient(x:number,y:number,x2:number,y2:number,colors:string[]){const g=this.ctx.createLinearGradient(x,y,x2,y2);colors.forEach((color,i)=>g.addColorStop(i/Math.max(1,colors.length-1),color));return g;}
 private arch(x:number,y:number,w:number,h:number,color:string){const c=this.ctx;c.beginPath();c.moveTo(x,y+h);c.lineTo(x,y+w*.5);c.arc(x+w*.5,y+w*.5,w*.5,Math.PI,0);c.lineTo(x+w,y+h);c.closePath();c.fillStyle=color;c.fill();}
 private backdrop(src:string,parallax=0){const image=Art.image(src);if(!image)return false;const c=this.ctx,scale=Math.max(this.w/image.naturalWidth,this.h/image.naturalHeight)*1.045;const w=image.naturalWidth*scale,h=image.naturalHeight*scale;const x=(this.w-w)*.5+clamp(parallax,-(w-this.w)*.48,(w-this.w)*.48),y=(this.h-h)*.45;c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(image,x,y,w,h);return true;}
 private fallback(arena:number,time:number,cam:number){const c=this.ctx,w=this.w,h=this.h,a=D.arenas[arena]||D.arenas[0],par=(cam-640)*.03;c.fillStyle=this.gradient(0,0,0,h,[...a.sky,a.sand]);c.fillRect(0,0,w,h);this.ellipse(w*.72-par,h*.16,36,36,'#f5d99b');
 for(let row=0;row<3;row++){const y=h*(.26+row*.135);c.fillStyle=row%2?a.stone:arena===1?'#5b5251':'#d5b88b';c.fillRect(0,y,w,h*.135);for(let x=-70-par;x<w+80;x+=65){this.arch(x+10,y+8,39,h*.1,'#493b2d');this.line(x+1,y+3,x+1,y+h*.135,'#f3dca466',3);}c.fillStyle='#40291d77';c.fillRect(0,y+h*.125,w,3);}
 for(let i=0;i<Math.ceil(w/10);i++){const x=i*10,y=h*.51+(this.reduced?0:Math.sin(time*2+i)*1.8);this.ellipse(x,y,3,3,['#9b603e','#b39368','#745548'][i%3]);this.line(x,y+4,x,y+10,['#873b31','#3a7b80','#766934'][i%3],5);}
 c.fillStyle=a.sand;c.fillRect(0,h*.66,w,h*.34);for(const x of[w*.14,w*.86]){this.line(x,h*.24,x,h*.55,'#34291f',4);this.polygon([[x-19,h*.25],[x+19,h*.25],[x+16,h*.44],[x,h*.49],[x-18,h*.44]],a.banner);this.ellipse(x,h*.34,8,10,a.accent);}
 for(let i=0;i<90;i++){const x=hash(i+33)*w,y=h*.67+hash(i+76)*h*.33;this.line(x,y,x+hash(i)*6,y,'#71532a33',1);}}
 scenery(arena:number,time:number,cam=640){const c=this.ctx,w=this.w,h=this.h;arena=clamp(arena,0,2);c.setTransform(this.dpr,0,0,this.dpr,0,0);c.globalAlpha=1;if(!this.backdrop(Art.arenas[arena],-(cam-640)*.045))this.fallback(arena,time,cam);
 if(!this.reduced){const count=arena===1?21:12;for(let i=0;i<count;i++){const speed=arena===1?8:2.5,x=(hash(i+41)*w+time*(speed+hash(i)*8))%(w+12)-6,y=arena===1?h-(hash(i+66)*h+time*(12+hash(i)*15))%h:hash(i+61)*h*.88+Math.sin(time+i)*4;this.ellipse(x,y,arena===1?1.4:1.1,arena===1?2:1,arena===1?'#ffc36b8a':'#fff2c25c');}
 if(arena===1){for(const x of[w*.075,w*.925]){const glow=c.createRadialGradient(x,h*.64,1,x,h*.64,w*.22);glow.addColorStop(0,`rgba(255,150,42,${.12+Math.sin(time*6+x)*.035})`);glow.addColorStop(1,'#ff962a00');c.fillStyle=glow;c.fillRect(x-w*.22,h*.64-w*.22,w*.44,w*.44);}}else{const ray=this.gradient(0,0,w,h,['#ffe7a000','#ffeac514','#fff6c000']);c.fillStyle=ray;c.beginPath();c.moveTo(w*.75,0);c.lineTo(w*.93,0);c.lineTo(w*.48,h);c.lineTo(w*.17,h);c.closePath();c.fill();}}
 const edge=c.createRadialGradient(w*.5,h*.53,Math.min(w,h)*.28,w*.5,h*.55,Math.max(w,h)*.8);edge.addColorStop(0,'#36201800');edge.addColorStop(1,arena===1?'#22172055':'#452a161e');c.fillStyle=edge;c.fillRect(0,0,w,h);
 }
 weapon(item:T.Item,x:number,y:number,angle:number,scale=1){this.character.weapon(item,x,y,angle,scale);}
 fighter(f:T.Fighter,x:number,y:number,scale:number,clock:number,showShadow=true){this.character.draw(f,x,y,scale,clock,showShadow,this.reduced);}
 render(e:ArenaEngine,dt=1/60){const w=this.w,h=this.h,c=this.ctx,dist=Math.abs(e.player.x-e.enemy.x);const target=Math.min(clamp(w/(dist+204),.53,1.56),h/253),smooth=1-Math.exp(-dt*6);this.zoom=mix(this.zoom,target,smooth);this.camera=mix(this.camera,(e.player.x+e.enemy.x)*.5,smooth);this.scenery(e.encounter.arena,e.clock,this.camera);const floor=h*.8;c.save();if(!this.reduced&&e.shake>0)c.translate(Math.sin(e.clock*121)*e.shake,Math.cos(e.clock*99)*e.shake*.4);const sx=(x:number)=>w*.5+(x-this.camera)*this.zoom;
 for(const f of[e.enemy,e.player]){if(['light','heavy','special'].includes(f.state)&&!this.reduced){const timing=ArenaEngine.timing(f),phase=f.elapsed/Math.max(.01,f.duration);if(phase>timing.start&&phase<timing.end+.1){const outer:T.Point[]=[],inner:T.Point[]=[];for(let i=0;i<9;i++){const r=ArenaEngine.pose(f,Math.max(f.duration*timing.start,f.elapsed-i*.013));outer.push({x:sx(f.x+r.tip.x*f.face),y:floor+(f.y+r.tip.y)*this.zoom});inner.push({x:sx(f.x+mix(r.hand.x,r.tip.x,.45)*f.face),y:floor+(f.y+mix(r.hand.y,r.tip.y,.45))*this.zoom});}
 this.polygon([...outer.map(p=>[p.x,p.y]),...inner.reverse().map(p=>[p.x,p.y])],f.state==='special'?'#ffca6080':'#fff5d24d','');c.beginPath();outer.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.strokeStyle=f.state==='special'?'#ffd57b':'#fff4c8';c.lineWidth=f.state==='heavy'?3.5:2.5;c.stroke();}}
 if(f.rage>=100&&f.hp>0&&!this.reduced){c.globalAlpha=.18+Math.sin(e.clock*5)*.05;this.ellipse(sx(f.x),floor+2,46*this.zoom,8*this.zoom,'#ffd163');c.globalAlpha=1;}this.fighter(f,sx(f.x),floor+f.y*this.zoom,this.zoom,e.clock);
 if(f===e.enemy&&['heavy','special'].includes(f.state)&&f.elapsed/Math.max(.01,f.duration)<ArenaEngine.timing(f).start){const x=sx(f.x),y=floor+(f.y-220)*this.zoom;this.polygon([[x,y-12],[x+12,y],[x,y+12],[x-12,y]],'#b83025','#ffe1a0',2);c.font='900 16px Georgia';c.textAlign='center';c.fillStyle='#fff8d4';c.fillText('!',x,y+5);}}
 for(const p of e.particles){c.globalAlpha=clamp(p.life/p.maxLife,0,1);const x=sx(p.x),y=floor+p.y*this.zoom;if(p.type==='dust')this.ellipse(x,y,p.size*this.zoom,p.size*this.zoom*.55,p.color);else this.line(x,y,x-p.vx*.018,y-p.vy*.018,p.color,p.size*this.zoom);}c.globalAlpha=1;
 for(const f of e.floats){c.globalAlpha=clamp(f.life*2,0,1);c.font=`900 ${f.size+2}px 'Alegreya Sans',system-ui`;c.textAlign='center';c.strokeStyle='#3a221b';c.lineWidth=4;c.lineJoin='round';c.strokeText(f.text,sx(f.x),floor+f.y*this.zoom);c.fillStyle=f.color;c.fillText(f.text,sx(f.x),floor+f.y*this.zoom);}c.globalAlpha=1;c.restore();
 if(e.intro>0){const y=h*.35,bw=Math.min(w*.86,430),x=(w-bw)*.5;c.save();this.polygon([[x,y],[x+bw,y],[x+bw-12,y+25],[x+bw,y+54],[x,y+54],[x+12,y+26]],'#7f2824','#e7bb61',2.5);this.line(x+17,y+5,x+bw-17,y+5,'#dc9d56',1);this.line(x+17,y+48,x+bw-17,y+48,'#dc9d56',1);c.font=`900 ${Math.min(27,w*.067)}px 'Cinzel Decorative',Georgia`;c.textAlign='center';c.strokeStyle='#432016';c.lineWidth=2;c.strokeText(e.intro>.55?'PREPARE-SE':'LUTEM!',w*.5,y+36);c.fillStyle='#ffe3a1';c.fillText(e.intro>.55?'PREPARE-SE':'LUTEM!',w*.5,y+36);c.restore();}
 }
 portrait(f:T.Fighter,time:number,arena=0){const c=this.ctx,w=this.w,h=this.h;f.walk=time*2;this.scenery(arena,time);c.fillStyle=this.gradient(0,h*.45,0,h,['#40261a00','#38241970']);c.fillRect(0,h*.45,w,h*.55);const scale=Math.min(h/259,w/176),x=w*.43,base=h*.91;this.ellipse(x,base+4,w*.36,Math.max(5,h*.032),'#674427',INK,1.5);this.ellipse(x,base,w*.36,Math.max(5,h*.028),'#c8a571','#f1d99b',1.2);this.fighter(f,x,base-2,scale,time);c.fillStyle=this.gradient(0,h*.92,0,h,['#36211500','#362115aa']);c.fillRect(0,h*.92,w,h*.08);}
}
