import {CultivationTypes as C} from './CultivationTypes';
export type BeastAnatomy='wolf'|'raptor'|'tortoise'|'salamander'|'stag'|'lynx'|'lion'|'wyrm';
export interface BeastSpeciesEntry {
 id:string; name:string; number:number; nature:C.Nature; archetype:C.Archetype; aspect:C.Aspect;
 rarity:'Comum'|'Raro'|'Épico'|'Lendário'; anatomy:BeastAnatomy; family:string; habitat:string;
 color:string; accent:string; light:string; description:string; observation:string;
 passive:{name:string;description:string}; techniques:{name:string;description:string}[];
 ultimate:{name:string;description:string}; evolutions:string[]; starter:boolean;
}
/** Original species catalog, adapted from the prototype. No gameplay hooks into the arena. */
export const BeastSpecies:readonly BeastSpeciesEntry[]=[
 {id:'pyrofang',name:'Pyrofang',number:1,nature:'Fogo',archetype:'Predador',aspect:'Voraz',rarity:'Raro',anatomy:'wolf',family:'Lupina',habitat:'Terras Rubras',color:'#a3442e',accent:'#f8ae45',light:'#ec8149',description:'Um lobo de pelagem ferruginosa e crista de brasas. A chama acompanha sua respiração, nunca abandona o próprio corpo.',observation:'Fareja o vento antes de correr. A cauda incandescente denuncia seu estado de alerta.',passive:{name:'Sangue Incandescente',description:'Vocação ofensiva: manter sequências de ataques.'},techniques:[{name:'Presa Ardente',description:'Investida frontal seguida de uma mordida ígnea.'},{name:'Passo de Cinzas',description:'Deslocamento evasivo envolto em brasas.'}],ultimate:{name:'Caçada Solar',description:'Sequência de perseguições com explosão final.'},evolutions:['Fenrir Solar','Lobo do Eclipse'],starter:true},
 {id:'stormhawk',name:'Stormhawk',number:2,nature:'Raio',archetype:'Duelista',aspect:'Tempestuoso',rarity:'Raro',anatomy:'raptor',family:'Aquilina',habitat:'Picos da Tormenta',color:'#45677e',accent:'#f8d867',light:'#8bcbd6',description:'Ave de rapina com penas azuis de borda metálica. Suas asas armazenam cargas nas correntes de altitude.',observation:'Paira sem perder o alvo de vista. Alterna batidas amplas com mergulhos muito curtos.',passive:{name:'Olhos da Tempestade',description:'Vocação de precisão e resposta veloz.'},techniques:[{name:'Garra Voltaica',description:'Golpe concentrado das garras eletrificadas.'},{name:'Mergulho Celeste',description:'Ataque oblíquo que atravessa a linha de defesa.'}],ultimate:{name:'Julgamento do Céu',description:'Descarga acumulada sobre uma área de impacto.'},evolutions:['Roc Trovejante','Águia Celestial'],starter:false},
 {id:'stoneback',name:'Stoneback',number:3,nature:'Terra',archetype:'Guardião',aspect:'Ancestral',rarity:'Comum',anatomy:'tortoise',family:'Quelônia',habitat:'Desfiladeiro Antigo',color:'#727b55',accent:'#dbc986',light:'#a9ae79',description:'Quelônio de carapaça pétrea, marcado por veios dourados. Sustenta o peso do casco sem perder o equilíbrio.',observation:'Recolhe a cabeça ao ouvir metal. Anda com passos firmes e intervalados.',passive:{name:'Carapaça Ancestral',description:'Vocação de proteção e estabilidade de postura.'},techniques:[{name:'Investida Rochosa',description:'Arranque curto com o casco voltado ao oponente.'},{name:'Bastião',description:'Posição de guarda reforçada pela essência mineral.'}],ultimate:{name:'Queda Continental',description:'O peso do casco converte-se em onda de impacto.'},evolutions:['Titã de Granito'],starter:true},
 {id:'tideclaw',name:'Tideclaw',number:4,nature:'Água',archetype:'Predador',aspect:'Sereno',rarity:'Comum',anatomy:'salamander',family:'Anfíbia',habitat:'Costa de Nácar',color:'#267b82',accent:'#e1bf76',light:'#74bdb4',description:'Predador anfíbio de guelras abertas, dorso azul e cauda achatada. Alterna aproximações silenciosas com arrancadas.',observation:'O ventre fica rente ao solo. Sua cauda oscila para corrigir a direção.',passive:{name:'Sangue das Marés',description:'Vocação de mobilidade e ataques encadeados.'},techniques:[{name:'Garra de Maré',description:'Corte lateral impulsionado por água.'},{name:'Fluxo Rápido',description:'Deslocamento baixo para reposicionar o corpo.'}],ultimate:{name:'Dilúvio Predatório',description:'Torrente curta seguida de ataque de aproximação.'},evolutions:['Leviatã Menor'],starter:false},
 {id:'thornstag',name:'Thornstag',number:5,nature:'Natureza',archetype:'Guardião',aspect:'Harmônico',rarity:'Raro',anatomy:'stag',family:'Cervina',habitat:'Bosque Viridiano',color:'#715f3c',accent:'#b2d076',light:'#bca777',description:'Cervo de galhada viva. Ramos e folhas crescem junto aos chifres; o brilho do peito acompanha o ritmo da floresta.',observation:'Ergue a cabeça antes de cada passo. As folhas tremem mesmo quando não há vento.',passive:{name:'Coração Verde',description:'Vocação de sustentação e controle de espaço.'},techniques:[{name:'Galhada Espinhosa',description:'Avanço que usa os chifres como barreira.'},{name:'Raízes Vivas',description:'A essência vegetal dificulta a aproximação rival.'}],ultimate:{name:'Floresta Desperta',description:'Manifestação de raízes ao redor do cultivador.'},evolutions:['Cervo Ancestral'],starter:true},
 {id:'nightlynx',name:'Nightlynx',number:6,nature:'Umbral',archetype:'Duelista',aspect:'Lunar',rarity:'Épico',anatomy:'lynx',family:'Felina',habitat:'Ruínas do Eclipse',color:'#504762',accent:'#b4a1ef',light:'#817593',description:'Felino de orelhas pontiagudas e cauda curta. As marcas do lombo quase desaparecem quando ele se agacha.',observation:'Move as patas sem deslocar os ombros. As orelhas acompanham sons fora de sua visão.',passive:{name:'Passo Silencioso',description:'Vocação de esquiva e abertura crítica.'},techniques:[{name:'Garra Sombria',description:'Ataque rápido com as duas patas dianteiras.'},{name:'Salto Noturno',description:'Salto baixo com mudança brusca de posição.'}],ultimate:{name:'Caçada do Eclipse',description:'Sucessão de saltos e golpes pelas aberturas da guarda.'},evolutions:['Lince do Vazio'],starter:false},
 {id:'sunmane',name:'Sunmane',number:7,nature:'Solar',archetype:'Colosso',aspect:'Solar',rarity:'Épico',anatomy:'lion',family:'Leonina',habitat:'Planície Dourada',color:'#b38b4a',accent:'#f5d477',light:'#e3ba6a',description:'Leão de juba monumental, semelhante a um disco solar. A cabeça permanece erguida mesmo sob ventos fortes.',observation:'A juba atrasa ligeiramente em relação ao corpo. Cada passo carrega o peso do peito.',passive:{name:'Majestade Solar',description:'Vocação de impacto e pressão ofensiva.'},techniques:[{name:'Rugido Radiante',description:'Pulso frontal para interromper aproximações.'},{name:'Pata Solar',description:'Golpe pesado que concentra força em uma única pata.'}],ultimate:{name:'Coroa do Meio-Dia',description:'Explosão de luz ao redor da juba manifestada.'},evolutions:['Leão Celestial'],starter:false},
 {id:'mistwyrm',name:'Mistwyrm',number:8,nature:'Água',archetype:'Espírito',aspect:'Abissal',rarity:'Lendário',anatomy:'wyrm',family:'Dracônica',habitat:'Lago Nebuloso',color:'#4e8696',accent:'#d9caa0',light:'#a8d8d8',description:'Serpente dracônica que parece nadar na névoa. Possui longos bigodes sensoriais e crista de escamas claras.',observation:'O corpo descreve curvas sucessivas. A cabeça flutua antes de iniciar uma volta.',passive:{name:'Corpo de Névoa',description:'Vocação de controle espiritual e alcance.'},techniques:[{name:'Sopro Nebuloso',description:'Névoa condensada projetada à frente.'},{name:'Espiral Etérea',description:'Giro serpentino com defesa de aproximação.'}],ultimate:{name:'Mar Sem Forma',description:'Manifestação extensa da essência aquática.'},evolutions:['Wyrm Abissal','Dragão das Nuvens'],starter:false}
];
